### ISSUE TITLE
Add archive.org

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#112]
https://archive.org/details/@jason_scott
https://archive.org/details/@webbreacher

**Comment by kpcyrd** [comment]
It seems this was implemented in the meantime: https://github.com/WebBreacher/WhatsMyName/blob/c140bb65778eddb039d25b756dcf0bb062bf6f48/web_accounts_list.json#L929-L939

**Comment by WebBreacher** [comment]
yes...maybe the title of the issue should change to Modify archive.org?

**Comment by WebBreacher** [comment]
The existing Internet Archive is good for searching for a user in any content. The new one (working on it now) will look for an archive.org user account for the specific user.

**Comment by WebBreacher** [comment]
added
