### ISSUE TITLE
broken site - imgur

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#135]
-  Looking up http://imgur.com/user/test
      !  ERROR: BAD DETECTION STRING. "Gallery comments" was not found on resulting page.

**Comment by WebBreacher** [comment]
imgur is now using API calls to load page content making our technique of checking an account more challenging.

Visiting a page like https://imgur.com/user/sillybilly0401/about loads (using XHR) pages like https://api.imgur.com/account/v1/accounts/sillybilly0401?client_id=546c25a59c58ad7 which have unique (and most likely expiring) tokens as client_id.

**Comment by mccartney** [comment]
onlyfans (#138) seems to be using the same technique (field names differ though).

**Comment by WebBreacher** [comment]
disabled in #181

**Comment by WebBreacher** [comment]
Added to https://github.com/WebBreacher/WhatsMyName/wiki/Problem-Removed-Sites
