### ISSUE TITLE
broken site - skyscanner

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#141]
-  Looking up https://www.trip.skyscanner.com/user/jay-bluher
      !  ERROR: BAD DETECTION STRING. "First Reviews" was not found on resulting page.

**Comment by mccartney** [comment]
Now they say:
> Trip by Skyscanner (formerly known as Gogobot and Trip.com) no longer operates as an independent website or mobile app. All content can now be viewed on the main Skyscanner website and mobile apps (ios | android).
> We look forward to seeing all the reviews and photos from your future travel adventures!

Are profiles a discontinued service?

**Comment by WebBreacher** [comment]
Closing
