### ISSUE TITLE
broken site - smite

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#142]
-  Looking up http://smite.guru/profile/pc/RayGunRushi
      !  ERROR: BAD DETECTION STRING. "Playtime</div>" was not found on resulting page.

**Comment by spotlightc** [comment]
https://smite.guru/profile/3481160-RayGunRushi 
added numbers to URL, need to remove from project

**Comment by WebBreacher** [comment]
removed this in #181
