### ISSUE TITLE
`account_missing_string` and `account_missing_code` are not used

### ISSUE THREAD

**Issue by mccartney** [WebBreacher/WhatsMyName#159]
## Context
The tool seems to be designed to run in two different modes:
- with `-u` specified -> then it checks all the services for the given name (the main use)
- without `-u` -> then the intent seems to be to validate the service mapping, whether our JSON is a proper description of the service behaviors

## Assessment of the current code

From programming point of view: neither `account_missing_string` or `account_missing_code` fields are being used.
From functional point of view - the tool cannot reliably distinguish between three different situations: server error (the services do have some problems), server behavior got changed (i.e. their responses are now different), and a missing account.

## Suggestion
I suggest to change the Python script to establish this behavior:

### with `-u` specified
open the URL with account name specified, and then:
- if existence string/codes match, then it's a **match**
- if missing string/codes match, then it's a **non-existing account**
- if neither, then it's an **error**

### without `-u`
Two rounds of checks are performed:
1. open the sites for each of the `known_accounts`, and:
- if existence string/codes match, then it's **OK**
- else, then it's an **error**
(note we don't use the `account_missing` here)
2. open each site with a random generated user name, and:
- if existence string/codes match, then it's a **error** (as it's unexpected)
- if missing string/codes match, then it's a **OK**
- if neither, then it's an **error**

**Comment by mccartney** [comment]
@WebBreacher does it make sense to you?
Does the suggestion capture your intent of the tool?

If so, I am happy to contribute a PR which implements the suggested behavior.

**Comment by WebBreacher** [comment]
Yes. And thank you for writing this up. Can we please leave the existing `/web_accounts_list_checker.py` tool and you start a fresh script to do the above? After, once functionality is confirmed, we'll remove the older script and yours will persist.
