### ISSUE TITLE
Consideration - non-public sites to be checked with attempt to sign up

### ISSUE THREAD

**Issue by mccartney** [WebBreacher/WhatsMyName#160]
**Currently** the tool only deals with sites with public profiles (no authentication required to see the profile).

**On top of that**, one could support sites with authentication and check if the profile name is already taken (by using the sign-up functionality). Obviously one would need to make sure the automation doesn't take the name if it's not taken - e.g. by supplying otherwise invalid parameters.

**Comment by WebBreacher** [comment]
i can see this as valuable but it would need to be a opt-in flag.

Additionally, keep in mind that the main point of this project is the JSON file. Other scripts use that so if we change the method of requesting, those scripts would also need to be altered.

**Comment by WebBreacher** [comment]
Going to close this as I'd like to keep this tool only finding the "open" site content. No logins or attempts.
