### ISSUE TITLE
Deviantart redirects to lowercase of profile name

### ISSUE THREAD

**Issue by mccartney** [WebBreacher/WhatsMyName#165]
Symptoms:
```
$ wget "https://www.deviantart.com/02wThRZv2wBY7hNPQIGM"
--2020-03-03 21:21:57--  https://www.deviantart.com/02wThRZv2wBY7hNPQIGM
Resolving www.deviantart.com (www.deviantart.com)... 54.230.231.87, 54.230.231.88, 54.230.231.94, ...
Connecting to www.deviantart.com (www.deviantart.com)|54.230.231.87|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /02wthrzv2wby7hnpqigm [following]
--2020-03-03 21:21:57--  https://www.deviantart.com/02wthrzv2wby7hnpqigm
Reusing existing connection to www.deviantart.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-03-03 21:21:57 ERROR 404: Not Found.
```

Consequences:
- generated names are redirected, so they don't (originally) return HTTP `404` status code
- valid profiles are redirected too, so we cannot rely on HTTP `200` status code

**Comment by mccartney** [comment]
And Freesound is an example of a site which does the opposite. Redirects a lower-case profile name to a proper name with its case-spelling:
```
$ wget "https://freesound.org/people/johndoe/"
--2020-03-03 21:40:54--  https://freesound.org/people/johndoe/
Resolving freesound.org (freesound.org)... 84.89.136.5
Connecting to freesound.org (freesound.org)|84.89.136.5|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /people/JohnDoe/ [following]
--2020-03-03 21:40:57--  https://freesound.org/people/JohnDoe/
Reusing existing connection to freesound.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 10032 (9,8K) [text/html]
```

**Comment by WebBreacher** [comment]
so... since we only provide a JSON to other projects, I'm guessing that we cannot do transformations of the user supplied username to make it work within this project. The script that uses our JSON file would need to add that logic or risk false negatives.

**Comment by mccartney** [comment]
We could enhance the JSON to indicate somehow how should the username be supplied. Obv. then it would be up to the other projects to honor that.

**Comment by WebBreacher** [comment]
True... wondering how many sites have this issue of case sensitivity. You found 2 so far... and they are minor ones (in the grand scheme of accounts, those platforms aren't major sources of info). I'm tempted to let it be without making changes to JSON.

Thinking maybe we change the name of the site to DeviantArt (Lowercase names only) or something. Thoughts?

**Comment by mccartney** [comment]
There has been one more which I saw with the same behavior as DeviantArt, but I didn't take note of it. Also - not the biggest one. So that would make it 3, which is not many I agree. Simplicity is more important.

**Comment by WebBreacher** [comment]
Agreed. If this becomes an issue, we will address it later.
