### ISSUE TITLE
Instagram Usernames with _ (underline) not found

### ISSUE THREAD

**Issue by osint4nsix** [WebBreacher/WhatsMyName#173]
Hi Micah,
I try to find faber_singt and several similar usernames with _ (_._a_n_i_k_a_._, o._._.schulze and so on) and does not found these accounts with whatsmyname.app

When I select Instagram and klick the OPEN Link the correct account was opened.

I make also tests with instantusername, namecheck and namevine. It works almost!
Thank you and best regards

Klaus
osint4nsix

**Comment by WebBreacher** [comment]
Can you tell me more about how you are running the application? Are you using the whatsmyname.app web site or the Python script that comes with this project or recon-ng?

**Comment by osint4nsix** [comment]
I use the whatsmyname.app!

**Comment by WebBreacher** [comment]
Thank you for that. Yesterday the app had an issue that caused it to malfunction. It is now working and, when I use the faber_singt name, it finds the Instagram account. Please confirm that it works for you too.

**Comment by osint4nsix** [comment]
I try it again. I search for a lon string with ZZZZZZZZZZZZZZZZZZZZZZZZZZ and then I make a search with the empty search field ... and receive results!
The search for faber_singt was not really successful. No found icon on the left. After klick on the open link on the right open the faber_singt account. But see the attached gif.
![Whatsmyname app](https://user-images.githubusercontent.com/62558202/77428689-cabd7980-6dd8-11ea-8675-d212c8c28a8b.gif)

**Comment by WebBreacher** [comment]
I cannot replicate your issue. There are security devices in place that you might be triggering by making odd requests like the "zzz". 

![image](https://user-images.githubusercontent.com/2359093/77429556-39d2a800-6db0-11ea-89d4-f052bfc5260c.png)

**Comment by osint4nsix** [comment]
I tested on several platforms with this results:
![Whatsmyname app-test](https://user-images.githubusercontent.com/62558202/77748791-3abe4080-7021-11ea-9b5a-ee9e7e36c1af.png)
