### ISSUE TITLE
Spotify false negative (similar to Twitter)

### ISSUE THREAD

**Issue by aaeissa** [WebBreacher/WhatsMyName#174]
Perhaps more testing might be needed, but the `"account_existence_string" : "Public Playlists"` is not found in the response body from a request to a valid Spotify profile when the current User-Agent is used (`{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0'}`). 

This is similar to the false negative that was previously reported for Twitter when that User-Agent is used as well. 

As a solution, I have changed the function definition to default to no custom UA:
```
def web_call(location, headers=None):
```

As well as implementing a simple check for these two sites to decide whether or not to use the custom User_Agent:

```
# do not pass in custom UA
if 'twitter' or 'spotify' in each.lower():
    r = web_call(each)

# pass in custom UA
else:
    r = web_call(each, headers)
```

If more of these sites are found, maybe there should be some reconsideration on the use of a single, custom User-Agent for all sites?

**Comment by WebBreacher** [comment]
disabled in #181

**Comment by WebBreacher** [comment]
So @aaeissa , using your function changes above, do Twitter and Spotify work? Twitter it seems as changed to use an HTML file that loads all user content via an API that requires the web browser to be authorized by the HTML/JS in the page.

**Comment by WebBreacher** [comment]
We are talking about this in #161 too.

**Comment by aaeissa** [comment]
@WebBreacher the solution I previously posted in March still works for Spotify, but no longer works for Twitter. As you said, there seems to be a change on Twitter's end.
