### ISSUE TITLE
Huge numbers of failed connections in threaded checker

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#183]
![2020-07-21_07-46-11](https://user-images.githubusercontent.com/2359093/88051275-57c5d480-cb26-11ea-94b7-1df272ac78eb.jpg)

Running the threaded checker from @salaheldinaz I get huge numbers of failed connections with `max tries exceeded` for sites that should respond. See image above.

Interesting thing is that the results from the threaded and non-threaded scripts ended up showing the exact sites not working. Thoughts?

**Comment by salaheldinaz** [comment]
Did you check your firewall, dns filter,... ?
I ran both scripts and they running correctly

**Comment by WebBreacher** [comment]
So those should not impact the run since I ran the threaded tool and received the errors and then immediately ran the unthreaded on and received positive results. Note that both tools showed same output at end.

Wondering if the threaded shows the HTTPS errors when the other non-threaded hides them?

**Comment by salaheldinaz** [comment]
The only change related to HTTPS was this edit  as `urllib3` is not a part of `requests`:

```
import urllib3

# Suppress HTTPS warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

Instead of : 
```
from requests.packages.urllib3.exceptions import InsecureRequestWarning

# Suppress HTTPS warnings
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
```

**Comment by WebBreacher** [comment]
not a functional issue as the threaded checker works very fast. closing issue
