### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by mccartney** [WebBreacher/WhatsMyName#200]
@WebBreacher I suggest you can consider "signing up" for advertising this repository for #Hacktoberfest.
I think it's a perfect repo for (some) even beginners wanting to contribute to open-source.
(Actually there's no need to "sign up" anywhere, just encourage people to participate by contributing to this repo)

See https://hacktoberfest.digitalocean.com/faq/ and "As a maintainer, how do I encourage contributions to my repos?" there if you are interested.

**Comment by mccartney** [comment]
Here's more info on how we as maintainers could be (more) open to new submissions in the Hacktoberfest: https://dev.to/devteam/preptember-start-getting-ready-for-hacktoberfest-this-month-58cn

**Comment by WebBreacher** [comment]
While I understand the idea behind this and would love the help on this project, I do not think this is the right effort for that support. As evidence for this, take a look at the PRs to "fix" the `requirements.txt` file in the repo.
