### ISSUE TITLE
Some assistance with troubleshooting please

### ISSUE THREAD

**Issue by swedishmike** [WebBreacher/WhatsMyName#215]
I've been butting my head against a wall with the testing of the Quora config that's below. 

I've tried with curl, wget as well as the browser and it _looks like_ I get the 404 and Page Not Found everywhere. However, when I try with `python3 ./check_online_presence.py -s quora` it errors on the non-existent check.

Are there any troubleshooting steps I'm missing? Do I need to run my own requests.get to get the exactly same output? Any input is appreciated.

```
{
   "name" : "Quora",
   "check_uri" : "https://www.quora.com/profile/{account}",
   "account_existence_code" : "200",
   "account_existence_string" : "Credentials",
   "account_missing_string" : "Page Not Found",
   "account_missing_code" : "404",
   "known_accounts" : ["John-Galan-5", "Alex-Clay"],
   "category" : "social",
   "valid" : true
}
```

**Comment by WebBreacher** [comment]
So there are a few switches in the checker scripts that can help a little bit. `-d` and `-se` as shown below.
![image](https://user-images.githubusercontent.com/2359093/97440572-ffa92600-18fd-11eb-929f-487cbb97a433.png)

I've also noticed that sites behind CloudFlare are really challenging to get consistent results from.

**Comment by swedishmike** [comment]
@WebBreacher  - sorry about that, should have actually read and tried to understand what the --help gave me. ;)

That helped lots - many thanks!
