### ISSUE TITLE
The link for recon-ng is broken

### ISSUE THREAD

**Issue by swedishmike** [WebBreacher/WhatsMyName#218]
The link for Recon-ng in the Readme.md is broken and should point to https://github.com/lanmaster53/recon-ng instead.

I was going to fix this and just submit a PR but then I realised that the other part is no longer valid either. I can't seem to find the Profiles module in the new repo. I've done a couple of searches in the repo but can't find any references to WhatsMyName any longer?

**Comment by WebBreacher** [comment]
fixed README.

the module is `profiler` in Recon-ng and Recon-ng has a separate repository for modules in its "Marketplace". Thanks for noticing the old content!
