### ISSUE TITLE
Colour output bit of a hit and miss on non-Linux os's

### ISSUE THREAD

**Issue by swedishmike** [WebBreacher/WhatsMyName#229]
I've had varying success with the coloured outpout on MacOS and Windows 10.

This comes down to the os checks and colour definitions in the scripts after what I can gather.

**Comment by WebBreacher** [comment]
I've been thinking about this and, if possible, i'd rather not include this non-core library in the scripts. I get the colorization issue and Win systems. Wonder if there is a different way to address it?

**Comment by swedishmike** [comment]
I fully see your point here... I took the easy way out and used something someone who had done the hard work had made public - I'll have a think and a play around to see what can be done 'more natively' too.

**Comment by WebBreacher** [comment]
I wonder if the issue with the existing script(s) is the detection of Windows systems and not how it makes the colors? Also, what Windows app are you using? In WSL (Windows Subsystem for Linux) terminal, I see the output like the Linux/Mac users do.

**Comment by swedishmike** [comment]
That could very well be it... I think the build I was having to use doesn't have/allow the WSL so it would have been the 'normal' one.

Maybe the easiest way would be add the following to the documentation: "If you want colors in Win10 - use WSL". ;)
