### ISSUE TITLE
Picuki

### ISSUE THREAD

**Issue by ghost** [WebBreacher/WhatsMyName#270]
Hi, your project is great. Picuki can be a good add, it's an other instagram viewer. It's a great website but there is a scroll limit. I find this website because Instagram blocks when open a lot of public profile.

ex : https://www.picuki.com/profile/(instagram)
https://www.picuki.com/search/(instagram)

I see WhatsMyName have some troubles with twitter and twitch. I don't know why

**Comment by WebBreacher** [comment]
Added.
