### ISSUE TITLE
Is "https://whatsmyname.app/ - Chris Poulter " source code available for download ? (GUI Interface)

### ISSUE THREAD

**Issue by minhanh1234** [WebBreacher/WhatsMyName#274]
Is the source for "https://whatsmyname.app/ - Chris Poulter" available for download.
I am very interested in hosting this application locally for personal use.

**Comment by WebBreacher** [comment]
It is not. However, the JSON of this project is along with several Python scripts that work locally.

**Comment by minhanh1234** [comment]
Great.. how do i return the result in a json format from web_accounts_list_checker.py or check_online_presence.py

**Comment by WebBreacher** [comment]
Right now, neither checker script outputs the data in JSON.

**Comment by WebBreacher** [comment]
The `web_accounts_list_checker.py` file can be modified to output in JSON format pretty simply. Pass a `-j` switch and it could switch the output format to JSON. Just need to come up with the JSON structure and implement.
