### ISSUE TITLE
[ ] New websites 

### ISSUE THREAD

**Issue by ghost** [WebBreacher/WhatsMyName#276]
It's me who create this issue too : #270.

- [ ]  I find Skypli, a Skype search engine : https://www.skypli.com/profile/(username)
- [ ]  I find 21buttons, a website interresting with username : https://www.21buttons.com/buttoner/(username)

Maybe instagram viewer can be good if instagram have some issues.

- [ ]  https://www.picuki.com/search/(instagram)

Some websites are usually false positives and they say "account found" (for exemple skyrock).

**Comment by WebBreacher** [comment]
Thank you for posting this. We will see about getting it added to the project!

**Comment by WebBreacher** [comment]
Sites are added! Thanks!
