### ISSUE TITLE
Requriements.txt creates dependancy issue (on Windows machine)

### ISSUE THREAD

**Issue by kimberlyJ69** [WebBreacher/WhatsMyName#290]
```
ERROR: Cannot install -r requirements.txt (line 1) and urllib3==1.26.5 because these package versions have conflicting dependencies.

The conflict is caused by:
The user requested urllib3==1.26.5
requests 2.24.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1
```

I believe maybe this is caused by the bumping of urllib3 version made June 2. 
Should maybe requests version be bumped to latest version as well? (2.25.1 at the moment)

**Comment by WebBreacher** [comment]
Agreed and thanks for noticing and making this issue. Would you like to do a PR to adjust the requirements file or shall I?

**Comment by kimberlyJ69** [comment]
I haven’t actually tested my proposed solution, hence why I made no PR. Feel free to do so :)

/
Kim

**Comment by WebBreacher** [comment]
Tested and this fixed the issue. THANK YOU @kimberlyJ69 for finding this issue, making this report, and suggesting the perfect fix for it. Really do appreciate your efforts here!
