### ISSUE TITLE
Check garmin and protonmail for false positives

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#293]

**Comment by WebBreacher** [comment]
### Protonmail

Protonmail's api has changed so that ANY email (valid or not) that is provided to https://api.protonmail.ch/pks/lookup?op=index&search=adasdafef43@protonmail.com will show positive results (i.e., there is an email there) instead of positive for some and negative for others. WhatsMyName was using this to find protonmail accounts and not it cannot discern truth from false positive.

I've poked the API and found the public key returning URL https://api.protonmail.ch/pks/lookup?op=get&search=webbreacheeegergergr@protonmail.com but that too provides positive data no matter what is presented. 

### Garmin

Changed detection string.

See #294

**Comment by seewhen** [comment]
Hi there,

I've been looking at the Proton issue and I've found a new endpoint you can query for valid accounts. 

The URL https://account.protonmail.com/api/users/available?Name=USERNAME is used during the sign-up phase for new accounts. A get request can be sent to this endpoint along with a username and the site will return a code as JSON indicating whether or not the username is in use or not. 

**Code: 1000**: (no message returned, so the username is available) 
**Code: 12101**: "Invalid input"
**Code: 12102**: "Username contains invalid characters"
**Code: 12106** :"Username already used"

Unfortunetly this endpoint requires the header "x-pm-appversion" with the value "WebAccount_4.4.1". If not you'll get the error "Missing x-pm-appversion header" when sending the get request. 

I know sending unique headers per request is not possible at the moment, so this comment is for documentation purposes should WMN decide to implement that feature.

**Comment by WebBreacher** [comment]
I'm working with OSINT Combine to implement the http_header value that @mklarz submitted in the #295 PR.

**Comment by WebBreacher** [comment]
Protonmail is now being checked in the hosted app. We changed the format of the http_headers key/value.
