### ISSUE TITLE
Add sex/dating sites

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#326]
FrenchPI's Start.me has many dating and sex sites that we can add. Below is a raw list that may yield useful sites:

http://RomanceScams.org
http://archive.is/oJzq7
http://bdsm.com
http://hinge.co
http://inviteandmeet.com/
http://lavalife.com/
http://match.com
http://mosteligible.hinge.co/
http://pof.com
http://skipthegames.com/
http://slindir.com/
http://sugard.co/
http://sugarnights.com/
http://toffee.dating/
http://whatsyourprice.com
http://www.arrangement.com/
http://www.benderapp.com/
http://www.blackpeoplemeet.com/
http://www.casualxapp.com/
http://www.cupidmedia.com/
http://www.detectivefrancaisusa.com
http://www.frenchdetective.com
http://www.getwooapp.com/
http://www.growlrapp.com/
http://www.knkiapp.com/
http://www.okcupid.com
http://www.pewresearch.org/topics/online-dating/
http://www.pof.com/advancedsearch.aspx
http://www.pof.com/basicusersearch.aspx
http://www.polymatchmaker.com/
http://www.swinglifestyle.com
https://Extralunchmoney.com
https://alt.com/
https://badoo.com/
https://bigone.dating/
https://blindlee.com/
https://bumble.com/
https://chappyapp.com/
https://chaturbate.com/
https://clover.co/
https://coffeemeetsbagel.com/
https://curiouscat.me/
https://datemyschool.com/
https://dating.christianmingle.com
https://doublelist.com/
https://escortfish.ch/
https://escortindex.com/
https://fancentro.com/
https://feeld.co/
https://fetlife.com/
https://findafemdom.com
https://getonce.com/en
https://github.com/fbessez
https://github.com/tomlandia
https://hashtagopen.com/
https://hily.com/
https://hinge.co/
https://hornetapp.com/login
https://imlive.com
https://iwantclips.com/
https://lumenapp.com/
https://megacams.me/cam/search?modelname=
https://mutualapp.co/
https://muzmatch.com
https://nostringsattached.com/
https://nuitapp.com/
https://pure.app/app/en/onboarding
https://rayatheapp.com/
https://rd.vu/
https://secure.tagged.com
https://selfieyo.com/
https://soulsingles.com/
https://streamate.com/
https://t.co/XqtP9z0c6c
https://taimi.com/
https://tantanapp.com/en/
https://tastebuds.fm/
https://teddysgirls.net/
https://trulymadly.com/
https://watchmyfeed.com/
https://weareher.com/
https://whiplr.com/
https://www.affaird.com/
https://www.aisle.co/
https://www.bdsmsingles.com
https://www.beautifulpeople.com/en-US
https://www.blindfold.me/
https://www.blued.com/en/index.html
https://www.caribbeancupid.com/
https://www.chemistry.com/
https://www.chispa-app.com/en
https://www.collarspace.com/
https://www.cowboys4angels.com
https://www.cuddli.com
https://www.datingscout.com/
https://www.downapp.com/
https://www.eharmony.com/
https://www.elitesingles.com/
https://www.eros.com/
https://www.escort-ads.com/
https://www.farmersonly.com
https://www.fetish.com/
https://www.fetster.com/
https://www.firstmet.com
https://www.flutterdating.com
https://www.friendfinder-x.com/
https://www.fuck.com/
https://www.gaydar.net/register
https://www.getshipped.com
https://www.getsweatt.com/
https://www.gogetterdating.com/
https://www.gotinder.com
https://www.gotinder.com/@username
https://www.grindr.com
https://www.happn.com
https://www.happn.com/en/
https://www.haterdater.com/
https://www.hikiapp.com/
https://www.jackd.mobi/
https://www.joinxo.app/
https://www.kinkdapp.com/
https://www.latinopeoplemeet.com/
https://www.lovoo.com/
https://www.maincams.com/
https://www.manyvids.com/
https://www.meetic.fr
https://www.meetinthecove.com/
https://www.meetme.com
https://www.misstravel.com/
https://www.modelhub.com/
https://www.myfreecams.com
https://www.mylol.com/
https://www.niteflirt.com/landing/1a
https://www.ohlala.com/en
https://www.okcupid.com/
https://www.pheramor.com/
https://www.pickable.app/
https://www.quarantinetogether.com/
https://www.scruff.com/
https://www.secretbenefits.com/
https://www.seekingarrangement.com/
https://www.sextpanther.com/
https://www.singles50.com/
https://www.skout.com/
https://www.skyprivate.com/
https://www.slixa.com
https://www.smoredate.com/
https://www.southerngfe.com/
https://www.spokeo.com/
https://www.spotafriend.co/
https://www.sudyapp.com/#/
https://www.sugardaddymeet.com/
https://www.swindr.net/
https://www.swipehelper.com/
https://www.theinnercircle.co
https://www.theleague.com/
https://www.wecamgirls.com/
https://www.yubo.live/
https://www.zealmatch.com/
https://www.zoosk.com

**Comment by K2SOsint** [comment]
@WebBreacher  Not sure how relevant this list still is, but I will check which ones are already in the WhatsMyName and I will see which I can add in the coming weeks if that's ok.

**Comment by WebBreacher** [comment]
Yes please. I would like to add as many dating, sex, call-girl/boy, porn sites to the project as possible to assist people looking into humans that are being trafficked.

**Comment by K2SOsint** [comment]
**Added**
https://Extralunchmoney.com :ok_hand:
https://www.bdsmsingles.com :ok_hand:

**Not relevant  as a dating/sex website**
~~http://archive.is/oJzq7~~
~~http://www.frenchdetective.com~~
~~http://www.detectivefrancaisusa.com~~

**No public user list/app only**
http://whatsyourprice.com
http://match.com 
http://www.swinglifestyle.com
https://www.quarantinetogether.com/
http://www.growlrapp.com/

**No username in URL/with numbers/scrambled**
https://iwantclips.com/
https://www.spotafriend.co/

**Offline**
http://inviteandmeet.com/

**Other**
http://RomanceScams.org -> has lists of dating sites, will make different issue for this later on
http://lavalife.com/ -> has list of dating sites, will have to check for double mentions in this list

**To Do**

The rest... 😜

**Comment by C3n7ral051nt4g3ncy** [comment]
# Websites Checked [93]

<br>

~https://www.romancescams.org~
~https://archive.ph/oJzq7~
~https://bdsm.com~
~https://hinge.co~
~http://inviteandmeet.com~
~http://lavalife.com~
~http://match.com~
~http://mosteligible.hinge.co~
~https://www.pof.com~
~http://skipthegames.com~
~http://www.www.slindir.com~
~http://sugard.co~
~https://sugarnights.com~
~http://toffee.dating~
~https://www.whatsyourprice.com~
~http://www.arrangement.com~
~http://www.benderapp.com~
~https://www.blackpeoplemeet.com~
~https://www.casualxapp.com~
~https://www.cupidmedia.com~
~http://www.detectivefrancaisusa.com~
~http://www.frenchdetective.com/~
~https://getwooapp.com~
~https://www.growlrapp.com~
~http://www.knkiapp.com~
~https://www.okcupid.com~
~https://www.pewresearch.org/topic/internet-technology/lifestyle-relationships/online-dating/~
~http://www.pof.com/advancedsearch.aspx~
~https://www.pof.com/basicusersearch.aspx~
~https://www.polymatchmaker.com~
~https://www.swinglifestyle.com~
✅ **Found User**: https://extralunchmoney.com/user/Milfjugs
~https://alt.com~
~https://badoo.com/~
~https://bigone.dating~
~https://blindlee.com/~
~https://bumble.com~
~https://chappyapp.com/~
✅ **Found User**: https://chaturbate.com/pussylovekate/
~https://www.clover.co~
~https://coffeemeetsbagel.com~
~https://curiouscat.live/login~
~https://datemyschool.com/~
~https://www.christianmingle.com/en-us~
~https://doublelist.com~
~escortfish.ch~ forwards to ---> ~https://sumosear.ch~
~https://escortindex.com~
✅ **Found User**: https://fancentro.com/xisabelcortezx
~https://feeld.co~
~https://fetlife.com/users/sign_in~
~https://findafemdom.com~
~https://getonce.com/en~
~https://github.com/fbessez~
~https://github.com/tomlandia~
~https://hashtagopen.com~
~https://hily.com~
~https://hinge.co/~
~https://hornetapp.com~
~https://imlive.com/~
~https://iwantclips.com~
~https://lumenapp.com/~
✅ **Found User**: https://megacams.me/Nathalia17
~https://mutualapp.co~
~https://muzmatch.com/en-GB/~
~https://nostringsattached.com~
~https://nuitapp.com~
~https://pure.app/app/en/onboarding~
~https://rayatheapp.com~
~https://rd.vu/~
~https://secure.tagged.com~
~https://selfieyo.com/~
~https://soulsingles.com/
~https://streamate.com~
~https://t.co/XqtP9z0c6c~
~https://taimi.com~
~https://tantanapp.com/en~
~https://tastebuds.fm~
✅ **Found User**: https://teddysgirls.net/models/jaycee-starr
~https://trulymadly.com~
✅ **Found User**: https://watchmyfeed.com/zoe-marie
~https://weareher.com~
~https://whiplr.com~
~https://www.affaird.com~
~https://www.aisle.co~
✅ **Found User**: https://www.bdsmsingles.com/members/QueenieDee/
~https://www.beautifulpeople.com/en-US~
~https://www.blindfold.me~
~https://www.blued.com/en/index.html~
~https://www.caribbeancupid.com~
~https://www.chemistry.com~
~https://www.chispa-app.com/en~
✅ **Found User**: https://www.collarspace.com/countrylifeDom
✅ **Found User**: https://cowboys4angels.com/cowboy/jaxjames/

<br>

# Websites not yet checked/verified: [67 Sites left to check]

- https://www.cuddli.com/ 
- https://www.datingscout.com/
-  https://www.downapp.com/ 
- https://www.eharmony.com/ 
- https://www.elitesingles.com/ 
- https://www.eros.com/ 
- https://www.escort-ads.com/ 
- https://www.farmersonly.com/ 
- https://www.fetish.com/ 
- https://www.fetster.com/
- https://www.firstmet.com/ 
- https://www.flutterdating.com/
- https://www.friendfinder-x.com/ 
- https://www.fuck.com/ 
- https://www.gaydar.net/register 
- https://www.getshipped.com/
- https://www.getsweatt.com/
- https://www.gogetterdating.com/
- https://www.gotinder.com/ 
- https://www.gotinder.com/@username 
- https://www.grindr.com/
- https://www.happn.com/
- https://www.happn.com/en/
- https://www.haterdater.com/ 
- https://www.hikiapp.com/ 
- https://www.jackd.mobi/
- https://www.joinxo.app/ 
- https://www.kinkdapp.com/ 
- https://www.latinopeoplemeet.com/ 
- https://www.lovoo.com/ 
- https://www.maincams.com/
- https://www.manyvids.com/ 
- https://www.meetic.fr/ 
- https://www.meetinthecove.com/ 
- https://www.meetme.com/
- https://www.misstravel.com/ 
- https://www.modelhub.com/ 
- https://www.myfreecams.com/ 
- https://www.mylol.com/ 
- https://www.niteflirt.com/landing/1a
- https://www.ohlala.com/en 
- https://www.okcupid.com/ 
- https://www.pheramor.com/
- https://www.pickable.app/ 
- https://www.quarantinetogether.com/ 
- https://www.scruff.com/ 
- https://www.secretbenefits.com/ 
- https://www.seekingarrangement.com/
- https://www.sextpanther.com/ 
- https://www.singles50.com/ 
- https://www.skout.com/ 
- https://www.skyprivate.com/
- https://www.slixa.com/ 
- https://www.smoredate.com/ 
- https://www.southerngfe.com
- https://www.spokeo.com/ 
- https://www.spotafriend.co/ 
- https://www.sudyapp.com/#/ 
- https://www.sugardaddymeet.com/ 
- https://www.swindr.net/ 
- https://www.swipehelper.com/
- https://www.theinnercircle.co/
- https://www.theleague.com/ 
- https://www.wecamgirls.com/ 
- https://www.yubo.live
- https://www.zealmatch.com/ 
- https://www.zoosk.com/

**Comment by WebBreacher** [comment]
I've added a few of these to the JSON. Others I've checked and many are behind authwalls or just don't have web-accessible (non-app) data. I'm going to go ahead and close this "issue".
