### ISSUE TITLE
Error with account_existence_string

### ISSUE THREAD

**Issue by shizhu13** [WebBreacher/WhatsMyName#336]
File "web_accounts_list_checker.py", line 224, in check_site
    string_match = r.text.find(site['account_existence_string']) >= 0
KeyError: 'account_existence_string'

**Comment by WebBreacher** [comment]
Thanks for the error. Can you tell us more please? What operating system? What version of python? Did you just clone and run or did you customize the json or python? ...

**Comment by shizhu13** [comment]
windows 10

**Comment by WebBreacher** [comment]
1. Did you just clone and run or did you customize the json or python?
2. What command did you run on the commandline?

**Comment by shizhu13** [comment]
> 1. Did you just clone and run or did you customize the json or python?
> 2. What command did you run on the commandline?

no customize json and python
command: python web_accounts_list_checker.py -u john

**Comment by WebBreacher** [comment]
Am I right in that you get this error and the script still runs and gives you the found accounts? I just ran it, saw the error and it continued to find 194 sites with `john` on it.

**Comment by WebBreacher** [comment]
I think I've fixed the issue. Can you update your local files (`git pull` or `git fetch` or download the files again from github).
