### ISSUE TITLE
Show "pretty_uri" instead of "check_uri" in the results

### ISSUE THREAD

**Issue by P3run** [WebBreacher/WhatsMyName#338]
I found in docs the "pretty_uri" parameter but it is not used in the code. It would be nice to display it in the results.

**Comment by WebBreacher** [comment]
This parameter is used in the JSON (https://github.com/WebBreacher/WhatsMyName/blob/master/web_accounts_list.json) and can be used by the checker applications. For instance, the https://whatsmyname.app site uses it when you click on a discovered account.

The checker scripts in this Python repository do not use it as most people do not use WhatsMyName via our scripts but, instead, through other people's tools like Spiderfoot and WhatsMyName.app. 

Are you talking about us adding the pretty_uri to our scripts?

**Comment by P3run** [comment]
Yes, I should be more specific - I'm talking about web_accounts_list_checker.py script.

**Comment by WebBreacher** [comment]
OK. I can see why this will be important. I'll add it as a TODO item. Thanks!

**Comment by P3run** [comment]
Here is my attempt to solve it: https://github.com/WebBreacher/WhatsMyName/pull/342
