### ISSUE TITLE
possible website corruption

### ISSUE THREAD

**Issue by allyrobinson591** [WebBreacher/WhatsMyName#359]
Hi there- I use WhatsMyName fairly often and today when searching usernames my antivirus blocked a search to a potentially dangerous website. Here is a screenshot form my anti-virus software. It happens every time I search a name. 

![image](https://user-images.githubusercontent.com/98120973/150405582-81259ab0-d31c-4c52-a570-b2e6616374ae.png)

**Comment by WebBreacher** [comment]
Hi there. Not sure what is going on. Scanning that Polish site in URLScan https://urlscan.io/result/a070ab2e-9c90-4557-8eaa-6a6b84a4f555/, Pulsedive https://pulsedive.com/indicator/?ioc=dml6amVyLnBs#login and other online tools do not show active malware or compromise or even historical issues. Do you have more details about what the AV sees "wrong" with this site? Perhaps it might be flagged as a category of web site your system is not supposed to go to.

**Comment by allyrobinson591** [comment]
The AV is Sophos endpoint: it's possible that's the case. It doesn't say anything else. Here's what happens when I go there directly. 

![image](https://user-images.githubusercontent.com/98120973/150408063-6dc4db9c-f688-4fe6-9ae0-9677e249f4e1.png)

**Comment by WebBreacher** [comment]
Hmmm. https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/Mal~HTMLGen-A.aspx. I don't see other sites flagging this site. If you are running the tool locally, you can edit the JSON file and turn the valid flag to `"valid": false` and your system will not hit that site.

**Comment by P3run** [comment]
This site used to stream movies online. It seems that something strange has happened and now, when you click anything, it will redirect you to some ads. Maybe they have been hacked and that's why the antivirus marks it as dangerous.

**Comment by WebBreacher** [comment]
Now disabled in the tool thanks to @iamzewen
