### ISSUE TITLE
new sites requested

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#386]
These came in from "Faith" via the webform. I'm wondering if, for the ones that have userids that are numbers in the URLs, could we find a search feature and then look for positive results for searching like `https://example.com/search.php?name=webbreacher` 

1. https://models.com/models/rebecca-leigh-longendyke
2. https://www.livejasmin.com/en/free/girls/#!chat/AryaLopez
3. https://vipergirls.to/members/439080-Prettyvixen8841
4. https://www.sleazyneasy.com/members/463672/
6. https://vrsumo.com/vr-pornstars/aali-kali-1660.html
7. https://www.mercari.com/u/376359578

**Comment by iamzewen** [comment]
I've been looking at the models.com one and I've found this endpoint that we might be able to use: https://api.models.com/prosearch/sitesearch19-json.html?mdcsearch=USERNAME

The challenge we face by using that is that the result returns any hit for what you're searching for and it uses the "resultCount": field to indicate how many results there are for your search. They don't provide a direct link to the models page, but rather a shortened version like {"people":[{"slug":"models/USERNAME"

Example search for 'dahl' here: https://api.models.com/prosearch/sitesearch19-json.html?mdcsearch=dahl with a total of 6 hits. Note that the URL for each profile is separated by a dash, which also make it somewhat difficult. 

The other option is to use https://models.com/models/ACCOUNTNAME. That search will always yield "FILE NOT FOUND", but they will suggest the profile you might be looking for based on your search. We can most likely pick something from the list of suggestion to indicate a result or not. 

Thoughts?

**Comment by WebBreacher** [comment]
I think the `https://models.com/models/dahl` is probably more consistent with our project. Because if you submit the exact name of a model (`sarah-dahl`) you get their profile https://models.com/models/sarah-dahl. 

So with this URL, we would do the normal "must be an exact match" situation where we find a specific term/string on the positive profile page and then use the `FILE NOT FOUND` error page for the case where the profile is not found.
