### ISSUE TITLE
PSN Profiles

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#387]
I thought we had this in the project at one point but do not see it now.

`https://psnprofiles.com/SlimShaggy18`

**Comment by iamzewen** [comment]
I've played around with this and have implemented a check for this site locally. The downside to PSN is that it's case sensitive, unlike most of our checks. Do we still want to add it? If so I can do a PR for it.

**Comment by WebBreacher** [comment]
yes. lets add it please. and thank you

**Comment by iamzewen** [comment]
One small issue. So the site is case sensitive, but in a really weird way. 

If an account exists BUT you've not entered it the incorrect way in terms of lowercase/uppercase characters, you'll be re-directed.  
 
 Example: 
 
 The account SlimShaggy18 exists. We run our check for the nick 'slimshaggy18'. PSN will then give us a HTTP status 301 and re-direct us to the correct page with the right uppercase letters. 
 
 The challenge is that when we check for usernames that **don't** exist we're always given a HTTP 302 and 200 for correct usernames. 
 
 As far as I know we have no way of checking for multiple HTTP status codes or fetch the re-direct URL we're thrown. 
 
 Current JSON entry I have for PSN is this: 
 
 {
          "name" : "Playstation Network",
          "check_uri" : "https://psnprofiles.com/{account}",
          "account_existence_code" : "200",
          "account_existence_string" : "<span class=\"username\">",
          "account_missing_string" : "updatePsnUser",
          "account_missing_code" : "302",
          "known_accounts" : ["SlimShaggy18", "ikemenzi"],
          "category" : "gaming",
          "valid" : true
        },
        
        
Any ideas for a possible solution?

**Comment by WebBreacher** [comment]
Try this XHR endpoint and see if it works better (like an API): `https://psnprofiles.com/xhr/search/users?q=SlimShaggy18&inline=1`

**Comment by iamzewen** [comment]
PR 389 will fix this issue

**Comment by WebBreacher** [comment]
#390 closing
