### ISSUE TITLE
Fix Venmo detection string

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#391]
@iamzewen discovered the url for Venmo user accounts has changed.

**Comment by iamzewen** [comment]
PR 392 solves this issue. Venmo has made some design changes lately that made our old detection method obsolete. 

The main change that I can see is: 

Old accounts can still be visited via venmo.com/USERNAME
New accounts, or maybe those who have decided to on-board to the new design, will be available on https://account.venmo.com/u/USERNAME. 

New usernames visited via venmo.com/USERNAME will automatically re-direct to the new URL, account.venmo.com/u/USERNAME. 

Overall this change is great for us as we have a dedicated user URL and lots of detection methods on pages where accounts exist. We should monitor Venmo in the coming weeks/months to make sure we stay on top of any new design changes.

**Comment by WebBreacher** [comment]
#423 addressed this. Closing issue
