### ISSUE TITLE
Support HTTP POST method with body in addition to default GET

### ISSUE THREAD

**Issue by Unpublished** [WebBreacher/WhatsMyName#402]
Example:

Fill out form (without submitting) on `https://wordpress.com/start/user` and watch for network calls to `https://public-api.wordpress.com/rest/v1.1/signups/validation/user?http_envelope=1`

**Comment by WebBreacher** [comment]
This has long been a goal of mine as many sites require POSTs and won't respond to GETs. I suppose we could just add a `post_data` param and value and if there is something there, then send the request via POST. 

Would require:
1. Alerting downstream users to the change so they can alter their scripts/sites.
2. Changing the included checker Python scripts to use it.

Thoughts?

**Comment by WebBreacher** [comment]
Understood and those are solid suggestions. Any idea of how many sites use POST instead of GET that would need this feature?

**Comment by WebBreacher** [comment]
Sounds good. I'm going to reach out to those down-stream tool maintainers that use WMN and ask if they have any issues with this proposal. Then we implement.

**Comment by WebBreacher** [comment]
Moving this discussion to #414 and closing this since we WILL be doing it just have to decide how.
