### ISSUE TITLE
Add virustotal

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#416]
Community member suggested adding https://www.virustotal.com/gui/user/banana

**Comment by WebBreacher** [comment]
@C3n7ral051nt4g3ncy @K2SOsint either of you want to do this?

**Comment by C3n7ral051nt4g3ncy** [comment]
Yes sure

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher 

I have tried to add virustotal, tested it with 2 python scripts.
Online Presence checker returns -->  
```
[!] Profile not found at https://www.virustotal.com/gui/user/banana
[!] Profile not found at https://www.virustotal.com/gui/user/jack
```

Web Accounts List Checker returns -->

```
The following previously "valid" sites had errors:
     virustotal --> Bad detection string.
```

**Comment by WebBreacher** [comment]
Looks like virustotal has a CAPTCHA that blocks the python script from checking the site. Not sure if it'll impact the web version.

**Comment by C3n7ral051nt4g3ncy** [comment]
Ok, so I will add Virustotal and we can see if it impacts the wv.

**Comment by WebBreacher** [comment]
Checking on this...I don't see VT in the JSON. Can you check it and submit a PR when you have it?

**Comment by C3n7ral051nt4g3ncy** [comment]
copy.

**Comment by WebBreacher** [comment]
Added
