### ISSUE TITLE
Adding Clusterdafrica

### ISSUE THREAD

**Issue by C3n7ral051nt4g3ncy** [WebBreacher/WhatsMyName#439]
I  like to add a website called **Cluster Digital Africa**; it seems to be an African copy of Twitter. 
I am having a few issues with the JSON, maybe someone can help getting a good detection string. 
- This is what I have: 

```
          {
           "name" : "clusterdafrica",
           "check_uri" : "https://clusterdafrica.com/@{account}",
           "account_existence_code" : "200",
           "account_existence_string" : "Membre depuis -",
           "account_missing_string" : "- Page non trouvée!",
           "account_missing_code" : "302",
           "known_accounts" : ["mamadou", "konate"],
           "category" : "social",
           "valid" : true
          },
```

**Comment by WebBreacher** [comment]
so the python checkers might send as useragent that causes the website to give the 403 to prevent scraping.

**Comment by C3n7ral051nt4g3ncy** [comment]
> so the python checkers might send as useragent that causes the website to give the 403 to prevent scraping.

Ok, That is what I thought.

**Comment by WebBreacher** [comment]
Yes, some Python checkers use a different UserAgent to check the site. We will be implementing that soon in our new checker.

**Comment by WebBreacher** [comment]
Confirmed. It denies Python UserAgent. See the image below. 1- Tried with the detections you have in the issue. It was rejected with an HTTP 403 (Forbidden). 2 - I re-ran with the `check_online_presence.py` script which uses the Firefox UA and it worked. 3- Shows the UA.

![image](https://user-images.githubusercontent.com/2359093/179606459-ca7b3ed3-699d-439f-960b-3e2f06cba252.png)

So, with this info, go ahead and submit the PR for this as it WILL work, just not for all checkers.
