### ISSUE TITLE
add runkeeper

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#44]
https://runkeeper.com/user/stevewerby/

**Comment by bcoles** [comment]
This no longer works. `[Failed to render "pageContent". See log for details.]`

It appears authentication may be required (or the site is broken).

**Comment by N0rdmann** [comment]
why is this closed? 
There is no other way for guests to view activity maps....

**Comment by WebBreacher** [comment]
Hi @N0rdmann . This is closed as the detection mechanism we were using to locate profiles on runkeeper no longer worked reliably and we couldn't, at that time, find additional methods of locating and extracting the necessary details we needed to determine positive or negative results.

Looks like, although in web pages we do not see content showing there is an account (see image), the HTML indicates there is one. So we can try to add this back.
![image](https://user-images.githubusercontent.com/2359093/88718395-e7075500-d0ef-11ea-9e80-18db056056b2.png)

**Comment by WebBreacher** [comment]
Closing this issue unless kyou or someone can figure out how to access this data.
