### ISSUE TITLE
new community suggestions: sites to be added

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#491]
`https://ifunny.co/user/{account}`

`https://picsart.com/u/{account}`

From user: *IFLinfosec*

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher 
- picsart was added recently
- ifunny isn't possible to add I think, it returns a `401 `instead of `200 `, and gives a bad detection string with the python checker `web_accounts_list_checker.py`

**Comment by WebBreacher** [comment]
Looks like it just examines the UserAgent. You can see that by doing somethjing like `curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" -v https://ifunny.co/user/john654654` where you change the UserAgent submitted in the request. Without the change, it drops the connection. With the "Firefox", it gives valid results. The `check_online_presence.py` script alters its UA string and might work to check this.

Let's go ahead and add this using the best detection strings and codes we can; the ones from our browsers. We will let the downstream tools deal with the UA issue.

**Comment by C3n7ral051nt4g3ncy** [comment]
> @C3n7ral051nt4g3ncy - Looks like it just examines the UserAgent. You can see that by doing somethjing like `curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" -v https://ifunny.co/user/john654654` where you change the UserAgent submitted in the request. Without the change, it drops the connection. With the "Firefox", it gives valid results. The `check_online_presence.py` script alters its UA string and might work to check this.
> 
> Let's go ahead and add this using the best detection strings and codes we can; the ones from our browsers. We will let the downstream tools deal with the UA issue.

Does this look ok?

   ```
          },
          {
           "name" : "ifunny",
           "check_uri" : "https://ifunny.co/user/{account}",
           "account_existence_code" : "401",
           "account_existence_string" :"subscribers",
           "account_missing_string" : "404 - page not found",
           "account_missing_code" : "404",
           "known_accounts" : ["hacker", "john"],
           "category" : "misc",
           "valid" : true
         },
         {
```

**Comment by WebBreacher** [comment]
Please change the following line: `"account_existence_code" : "200",`

**Comment by C3n7ral051nt4g3ncy** [comment]
> Please change the following line: `"account_existence_code" : "200",`

Copy. Will do that right now and submit a PR.

**Comment by WebBreacher** [comment]
Closed with #502

**Comment by WebBreacher** [comment]
@C3n7ral051nt4g3ncy  - Just checked WMN.app and your detection works fine in browser. 

![image](https://user-images.githubusercontent.com/2359093/186037372-d9b5a9e2-cf78-4794-b123-1f818859b0a0.png)

**Comment by C3n7ral051nt4g3ncy** [comment]
> @C3n7ral051nt4g3ncy  - Just checked WMN.app and your detection works fine in browser. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/2359093/186037372-d9b5a9e2-cf78-4794-b123-1f818859b0a0.png)
> 
> 

That's good news and a relief. 👍
