### ISSUE TITLE
Script error with no output

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#529]
@yooper Can you check out why running the ` python3 ./whats_my_name.py -u Kash -s "truth_social"` gives no result, no error, and an empty list for the output?

**Comment by C3n7ral051nt4g3ncy** [comment]
> @yooper Can you check out why running the ` python3 ./whats_my_name.py -u Kash -s "truth_social"` gives no result, no error, and an empty list for the output?

My fault @WebBreacher + @Yooper , probably due to the `m_string` format.

**Comment by WebBreacher** [comment]
No @C3n7ral051nt4g3ncy that isn't it. With your fix I'm still not getting any response even with the `-d`, `-v`, and `-ce` flags. No response codes or anything. 
```
$ python3 ./whats_my_name.py -u Kash -s "truth_social" -v -d
[]
```

**Comment by C3n7ral051nt4g3ncy** [comment]
> No @C3n7ral051nt4g3ncy that isn't it. With your fix I'm still not getting any response even with the `-d`, `-v`, and `-ce` flags. No response codes or anything.
> 
> ```
> $ python3 ./whats_my_name.py -u Kash -s "truth_social" -v -d
> []
> ```

@WebBreacher Same for me, just tested for `truth_social`, and it's not in the `results table`, and its not in the `site error list` either.

Used the command:

`$ python3 whats_my_name.py -u realDonalTrump --format table`

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher I haven't had time to look at the code in the new python script, the bug may be due to having 2 `wmn-data.json` files. 

Maybe its pulling responses from this [wmn-data.json(https://github.com/WebBreacher/WhatsMyName/tree/main/whatsmyname/tests/data)?

<br>

As `truth_social` is the newest site addition and the script isn't returning any info about it, it means it's searching the other `wmn-data.json`.

**Comment by yooper** [comment]
No data is being returned because the default `wmn-data.json` is located at https://github.com/WebBreacher/WhatsMyName/blob/main/whatsmyname/app/resources/wmn-data.json, this default file does not have the `truth_social` website defined.

**Comment by WebBreacher** [comment]
Ahh. OK. I'd like that default location to be the file in the root directory and not the nested one. This project is mainly used by scripts that just want that file so we keep it at the root level.
