### ISSUE TITLE
For scripts `whats_my_name.py` and `validat...py`, wrap/truncate URL output to table at 50 characters

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#551]
URL table field should be wrapped or truncated at ~ 50 chars otherwise the output wraps around the screen and destroys the table CLI output format. 

cc: @yooper

**Comment by yooper** [comment]
@WebBreacher , this issue can be closed. The PR https://github.com/WebBreacher/WhatsMyName/pull/567 added this feature.

**Comment by WebBreacher** [comment]
Confirmed. Thanks @yooper
