### ISSUE TITLE
Second ebay url

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#553]
@C3n7ral051nt4g3ncy:

@hatless1der showed me that Ebay has a "store" (`/str/`) and a "user" (`/usr/`) URL for each seller. Those are linked but can be different. We have the USR in the project already. Please add the STR like:

`https://www.ebay.com/str/thriftbooksstore`

which has a user profile of `https://www.ebay.com/usr/thrift.books`

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher This issue can now be closed. Site added.

**Comment by WebBreacher** [comment]
We will wait for the PR before closing. Please link to this issue #553 in the PR.
