### ISSUE TITLE
Mother load of new sites

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#555]
I found these sites that are focused around: finance, wishlists, XXXPORNXXX, and hobbies.

The first one is a POST and I'll take that.

| Site                                                                                                                         | Example URL                                                                    |
| ---------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ |
| POST - https://forumserver.twoplustwo.com/ajax.php?do=usersearch   DATA - securitytoken=guest&do=usersearch&fragment=Redsoxn |                                                                                |
| ~~http://paypal.me/{account}~~                                                                                                   | http://paypal.me/OCMermaid                                                     |
| ~~https://bio.link/{account}~~                                                                                                  | https://bio.link/adli_hm                                                       |
| ~~https://cafecito.app/{account}~~                                                                                               | https://cafecito.app/braftty                                                   |
| https://en.pronouns.page/@{account}                                                                                          | https://en.pronouns.page/@kissettka                                            |
| https://fansly.com/{account}/posts                                                                                           | https://fansly.com/castaway/posts, https://fansly.com/MeiMinato/posts          |
| https://frisk.chat/{account}                                                                                                 | https://frisk.chat/adrianna                                                    |
| ~~https://gfycat.com/@{account}~~                                                                                                | https://gfycat.com/@timviechanoi                                               |
| https://i.thechive.com/{account}                                                                                             | https://i.thechive.com/Shananigins82                                           |
| https://likee.video/search/{account}                                                                                         | https://likee.video/search/emily_stacy                                         |
| ~~https://mym.fans/{account}~~                                                                                                   | https://mym.fans/Unmissabl                                                     |
| https://namedrop.io/{account}                                                                                                | https://namedrop.io/aaminahshakur                                              |
| https://onlyfans.com/{account}                                                                                               | https://onlyfans.com/scottyjoe246free                                          |
| https://partme.com/{account}                                                                                                 | https://partme.com/cherryneko0628                                              |
| ~~https://resumes.actorsaccess.com/{account}~~                                                                                   | https://resumes.actorsaccess.com/veronicashelby                                |
| https://saweria.co/{account}                                                                                                 | https://saweria.co/adlihm                                                      |
| https://secure.donationpay.org/{account}/                                                                                    | https://secure.donationpay.org/rareimpact/                                     |
| https://shop.moso.moe/{account}/                                                                                             | https://shop.moso.moe/merryweather/                                            |
| https://shoutoutexpress.com/{account}                                                                                        | https://shoutoutexpress.com/KikiXKlout                                         |
| ~~https://slackholes.com/actor/{account}/~~                                                                                      | https://slackholes.com/actor/alexbreecooper/                                   |
| https://throne.me/u/{account}/wishlist                                                                                       | https://throne.me/u/serinide/wishlist, https://throne.me/u/kasiedilla/wishlist |
| https://tiltify.com/{account}/profile                                                                                        | https://tiltify.com/@sharki_b/profile                                          |
| https://trakteer.id/{account}/                                                                                               | https://trakteer.id/adli_hm/                                                   |
| https://trovo.live/{account}                                                                                                 | https://trovo.live/sharki_v                                                    |
| ~~https://www.cameo.com/search?q={account}~~                                                                                     | https://www.cameo.com/search?q=sarahall                                        |
| https://www.loyalfans.com/{account}                                                                                          | https://www.loyalfans.com/sentient_waifu                                       |
| ~~https://www.manyvids.com/results.php?keywords={account}~~                                                                     | https://www.manyvids.com/results.php?keywords=AlexBreeCooper                   |
| ~~https://www.nihbuatjajan.com/{account}~~                                                                                       | https://www.nihbuatjajan.com/adli_hm                                           |
| ~~https://www.redgifs.com/users/{account}~~                                                                                      | https://www.redgifs.com/users/alexbreecooper                                   |
| https://www.selfiepop.com/{account}                                                                                          | https://www.selfiepop.com/kassiebear1318                                       |
| https://www.sextpanther.com/{account}                                                                                        | https://www.sextpanther.com/rocky-emerson                                      |
| https://{account}.myportfolio.com/                                                                                           | https://artkonina.myportfolio.com/                                             |
| ~~https://{account}.sofurry.com/~~                                                                                               | https://reeden-landshey.sofurry.com/                                           |

**Comment by WebBreacher** [comment]
@C3n7ral051nt4g3ncy since there are many sites in here, if we have problems with any one of them, let's open another issue to work on it instead of making one long single issue here.

**Comment by C3n7ral051nt4g3ncy** [comment]
ok

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher: Reference to above, `Biolink` can now be crossed out as it has just been added in the PR #566

**Comment by WebBreacher** [comment]
#566 completes:

-     Airliners
-     Biolink
-     Steller
-     Social Tchncs
-     Inaturalist
-     Fandalism
-     Fine Art America

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher `Cafecito` can be crossed out, we already have `dribble` in the sites list which can also be crossed out

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher: `sofurry` has just been added.

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher: `myportfolio` has been added.

**Comment by C3n7ral051nt4g3ncy** [comment]
There is changes to do on the `PayPal link`, it's not the correct structure, I will try and amend.

**Comment by C3n7ral051nt4g3ncy** [comment]
### sites to cross out:

@WebBreacher: 

- `Paypal`
- `resumes.actorsaccess`
-  `mymfans`
- `gfycat`

**Comment by WebBreacher** [comment]
updated

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher: `nihbuatjajan.com` has also been added to WMN

**Comment by WebBreacher** [comment]
Closing
