### ISSUE TITLE
HTTP POST Site Output

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#558]
![image](https://user-images.githubusercontent.com/2359093/190534932-52634495-4b1e-4f64-9432-0ec68a530780.png)
@yooper - I'd like to work with you on more meaningful output for the HTTP POST case. We cannot just echo the URL since the data is not appearing in the URL. Also, I'm not sure POSTs are being eval'd correctly.

**Comment by yooper** [comment]
Good Morning @WebBreacher , feel free to assign the ticket to me.

What would the ideal output be for POST requests?

**Comment by WebBreacher** [comment]
This entry has a `uri_pretty` param/value pair. I think that would be the best thing.

![image](https://user-images.githubusercontent.com/2359093/190636137-84e4acf3-1153-4ed9-8ae2-6fff99f1fab8.png)
