### ISSUE TITLE
HTTP POST entry and output

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#560]
Related to #555 

POST - [https://forumserver.twoplustwo.com](https://forumserver.twoplustwo.com/ajax.php?do=usersearch) site has been added but:

There is no real negative result. The positive result has extra data but the negative result has the same HTTP response code and same data except is missing the positive string (`e_string`)

**Comment by C3n7ral051nt4g3ncy** [comment]
ok

**Comment by C3n7ral051nt4g3ncy** [comment]
@WebBreacher : Is there anything else to do regarding this issue or can it be closed?

**Comment by WebBreacher** [comment]
Yes it should stay open until the HTTP POST checking output is resolved by @yooper

**Comment by yooper** [comment]
We haven't implemented the POST functionality, yet in WMN. We do need to verify and confirm that the example, found in #555, is how we want POST data, within the `wmn.json` file.

**Comment by WebBreacher** [comment]
I believe that format for the data ` securitytoken=guest&do=usersearch&fragment=Redsoxn` would be preferred as that should be able to be cut and pasted into the data portion of the POST.

**Comment by yooper** [comment]
I plan on starting on this functionality this week.
