### ISSUE TITLE
Is validate_whats_my_name.py working properly?

### ISSUE THREAD

**Issue by jocejocejoe** [WebBreacher/WhatsMyName#571]
I noticed that a couple sites I added were no longer working on whatsmyname.app, for example Gettr.  I traced that back to commit 08f9dde which started checking for `e_string`, which seems to have changed in Gettr's API.

So I decided to try to use `validate_whats_my_name.py` to see if other sites were still OK, and it seems like it's not working properly, although I'm not sure what to expect for output.

I _think_ that `_validate_site()` is getting called for both valid ("known") and invalid (random) usernames for the test, but it's always comparing against e_code and e_string, not m_code and m_string for random invalid usernames. So I think that every "invalid name" test will look like a failure to the script (i.e. it does not properly detect that the random account does not exist.)

But as I try to fix it up, I'm getting confused about what to expect. Can you explain how the validate script should work, i.e. what _should_ be shown for good and/or bad site records?

**Comment by WebBreacher** [comment]
cc: @yooper

**Comment by yooper** [comment]
@WebBreacher you can assign to me. I planned on working on the validation script to improve its overall quality. @jocejocejoe thanks for reporting the issue.

**Comment by jocejocejoe** [comment]
Thanks! To be clear, nothing wrong with commit 08f9dde AFAICT, it just exposed that there are existing site records which are no longer correct, once e_string is being properly tested, and that the validate script may not be up to the task of catching them.

**Comment by yooper** [comment]
@jocejocejoe , a couple days ago a PR got merged that makes it easier to test the validity of a site and includes additional debug information.  For your your example, run the following command, it will dump out the raw response and the response headers, which includes helpful information too. 

```sh
python whats_my_name.py -u yooper99999 -a -s gettr --verbose --format csv
```
