### ISSUE TITLE
Furaffinity's category

### ISSUE THREAD

**Issue by RedstoneLP2** [WebBreacher/WhatsMyName#573]
At the time of writing Furaffinity is in the XXXPORNXXX category of this project, while the actual site would (IMHO) fit better in ether the same category as Deviantart or the hobby category.

**Comment by WebBreacher** [comment]
Excellent catch and, after viewing a bunch of the content on the site, I agree. Switched it to `images` like deviantart. Thanks for catching this and the suggestion.
