### ISSUE TITLE
Output flag does not produce output file

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#582]
Running the command `python3 validate_whats_my_name.py -o ../../../Desktop/out1.txt` should output the table to a file and not the screen or, to a file AND the screen.

I understand we can redirect output using `>` and `>>` but the flag specifies it will create an output file.

cc: @yooper

**Comment by yooper** [comment]
Please feel free to assign to me.

**Comment by yooper** [comment]
There is couple things going on here:

1. If you don't specify either the CSV or JSON formats, the output file is not valid. If you do specify those formats, then an output file is created, in the specified location.
2. We have to change the default behavior from outputting to the screen, when the `-o` flag is given

I am not sure how to you want to handle the issue when no format is specified. Please advise..

**Comment by WebBreacher** [comment]
Resolved in #621 . Thank you @yooper
