### ISSUE TITLE
JSON output is not valid JSON

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#584]
Using the `--format json` opttion produces JSON-like output that is not valid. Let's make it valid JSON.

cc: @yooper

**Comment by yooper** [comment]
@WebBreacher , can you provide an example? ..
```
# EX
python whats_my_name.py -uyooper -szillow -a --format json
```
Feel free to message me in discord, if you do not want to post here.

**Comment by WebBreacher** [comment]
That returns `[{"http_status_code": 307, "generated_uri": "https://www.zillow.com/profile/yooper/", "username": "yooper"}]` which is lacking the JSON leading and trailing `{` and `}` and a parameter like `data`. I'd like proper JSON that is complete like:

`{ "data" : [{"http_status_code": 307, "generated_uri": "https://www.zillow.com/profile/yooper/", "username": "yooper"}]}`

**Comment by yooper** [comment]
@WebBreacher , 
JSON does not need to start with `{}` , it can start with `[]`. If you want the formatting different, that's fine, but I want to clarify the program already produces valid JSON. You can test by copying and pasting the JSON output into a JSON linter / validator online.
