### ISSUE TITLE
false positives and logic

### ISSUE THREAD

**Issue by elephantasticio** [WebBreacher/WhatsMyName#606]
Hi,

There is an edge case with one of the sites:

```json
        "name" : "Skyrock",
        "uri_check" : "https://{account}.skyrock.com/",
        "post_body" : "",
        "e_code" : 200,
        "e_string" : "s blog",
        "m_string" : "<title>Page not found - ",
        "m_code" : 404,
        "known" : ["alice", "bob"],
        "cat" : "social",
        "valid" : true
```

Problem is that for example https://this_doesnotexist.skyrock.com returns a 200 code but is not a valid account.

Our solution for this problem is both changing the site details AND the code logic (implemented in our own code):

```json
      "name": "Skyrock",
      "uri_check": "https://{account}.skyrock.com/",
      "post_body": "",
      "e_code": 200,
      "e_string": "<meta property=\"og:url\"",
      "m_string" : "<title>Page not found - ",
      "m_code" : 404,
      "known": ["alice","bob"],
      "cat": "social",
      "valid": true
```

Detection logic:
`if status_check and string_check and not (status_missing and string_missing): valid = True`

**Comment by WebBreacher** [comment]
Thanks for the submission and suggestions.

I've altered the `e_string` to be more complete/accurate in #608 

The logic of the whatsmyname.app site is privately managed by a third party. The WhatsMyName checker Python scripts are under development/change now and we will look into adding this logic.
