### ISSUE TITLE
add new youtube

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#607]
https://youtube.com/@MicahHoffman

**Comment by WebBreacher** [comment]
the existing YouTube User entry will match this new style of reaching a user's account. No action needed.

**Comment by C3n7ral051nt4g3ncy** [comment]
This is awesome thanks !!!! I had not thought about submitting this change with the new YT handle.

**Comment by WebBreacher** [comment]
Yeah...the new handle is basically just a redirect to the existing profile at the longer URL. 

I did add a new YouTube entry for channels since those have different URLs
