### ISSUE TITLE
Add spatial.io

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#612]
This is tech/VR - `https://www.spatial.io/@jake`

**Comment by WebBreacher** [comment]
I think this is going to be a POST at `https://api.spatial.io/users/v1/profile` with data=`{"username":"john"}` but am concerned that to access the API a prior POST is made that carries some auth info.

**Comment by C3n7ral051nt4g3ncy** [comment]
Maybe this issue can be closed, nothing works, need an auth token for the API.

**Comment by WebBreacher** [comment]
Understood and thanks for checking it out
