### ISSUE TITLE
Some sites seem to return false results

### ISSUE THREAD

**Issue by osint-tniso1** [WebBreacher/WhatsMyName#637]
IFTT, PinkBike and Wanelo seems to return fals results if the username has a dot in it. Everything after the dot seems to be ignored.
E.g. johnstewart.123. If you remove '.123' from the url in the result and refresh the site, the same page will return.

**Comment by WebBreacher** [comment]
Yes. This is a known issue that some sites truncate the username when a dot or dash are present. But this behavior is on their side and not something we can account for. Additionally, WMN is not set up to have the additional data about sites that would be impacted by dots. So we shift the searching to the user who will need to do perform additional searches.

Now if the IFTTT and other sites do not work anymore with non-dot usernames, that is something we have control over.
