### ISSUE TITLE
Returning error when running

### ISSUE THREAD

**Issue by Caso-Serio** [WebBreacher/WhatsMyName#639]
Hello, I apologize in advance if this is a dumb issue, I am attempting to use the profiler through Recon-ng on kali linux in VirtualBox. Everytime I run the profiler I am greeted with an "[Errno Extra data] 404: Not Found: 3" error. I don't know how to resolve it, any help would be greatly appreciated. Thank you.

**Comment by WebBreacher** [comment]
Hi there. Thanks for writing. Unfortunately the recon-ng profiler module is still trying to pull the older version of our project. We reached out to them earlier this year to ask that they update the tool and received no response. So the module will be broken until someone updates it in recon-ng. 

My suggestion is for you to use our python script or use the very easy to use Spiderfoot.net program.
