### ISSUE TITLE
ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by andre-santos1** [WebBreacher/WhatsMyName#641]
When I run:

`python3 whats_my_name.py -u username`

I get:

`Traceback (most recent call last):

  File "/home/osint/Programas/WhatsMyName/whats_my_name.py", line 2, in <module>

    from whatsmyname.main import check_for_presence

  File "/home/osint/Programas/WhatsMyName/whatsmyname/main.py", line 4, in <module>

    from whatsmyname.app.cli.args import get_default_args, arg_parser

  File "/home/osint/Programas/WhatsMyName/whatsmyname/app/cli/args.py", line 10, in <module>

    from whatsmyname.app.extractors.file_extractors import user_agent_extractor

  File "/home/osint/Programas/WhatsMyName/whatsmyname/app/extractors/file_extractors.py", line 4, in <module>

    from pydantic import parse_obj_as

  File "pydantic/__init__.py", line 2, in init pydantic.__init__

  File "pydantic/dataclasses.py", line 52, in init pydantic.dataclasses

    # __init__

ImportError: cannot import name dataclass_transform`

What should I do?

I'm using Ubuntu 22.04 and Python 3.10.6

Thanks!!!!

**Comment by C3n7ral051nt4g3ncy** [comment]
@andre-santos1 : Did you run `pip3 install -r requirements.txt` prior ?

Try also starting all over again, delete repo, git clone again, and then try.
Maybe conflicting modules, so make a `virtual environment`. See installation instructions.

**Comment by andre-santos1** [comment]
Yeap, I had run `sudo pip install -r requirements.txt` prior.

I deleted repo and reinstalled it but no luck. Same error with or without virtual environment.
Same error runing `pip3 install -r requirements.txt`.
I notice one thing though. I'm not sure if it's related but when I run `sudo pip install -r requirements.txt` (or `pip3 install requirements.txt` ) it states:


`ERROR: Cannot install -r requirements.txt (line 38) and poetry-core==1.1.0a7 because these package versions have conflicting dependencies.



The conflict is caused by:

    The user requested poetry-core==1.1.0a7

    poetry 1.1.14 depends on poetry-core<1.1.0 and >=1.0.7



To fix this you could try to:

1. loosen the range of package versions you've specified

2. remove package versions to allow pip attempt to solve the dependency conflict



ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by C3n7ral051nt4g3ncy** [comment]
@andre-santos1 : I think I get the issue, you have conflicting dependencies, this is why it would be better for you to work in a virtual environment. See here: https://github.com/C3n7ral051nt4g3ncy/python_virtual_environment

**Comment by andre-santos1** [comment]
It worked @C3n7ral051nt4g3ncy !!! Thanks for being so patient and so helpful!

**Comment by C3n7ral051nt4g3ncy** [comment]
@andre-santos1 My pleasure. Feel free to `close the issue as completed`.

**Comment by andre-santos1** [comment]
Completed
