### ISSUE TITLE
conflicting dependencies

### ISSUE THREAD

**Issue by Pepepy** [WebBreacher/WhatsMyName#644]
I am trying to install it in a virtualenv on a kali linux 2022 machine. When installing the dependencies I get the following error:

he conflict is caused by:
    The user requested crashtest==0.4.1
    cleo 2.0.0 depends on crashtest<0.5.0 and >=0.4.1
    clikit 0.6.2 depends on crashtest<0.4.0 and >=0.3.0; python_version >= "3.6" and python_version < "4.0"

I have tried in python3.6, python3.7, python3.8 and python3.10 environment and all give me the error.
Does anyone know how I can fix it?

**Comment by C3n7ral051nt4g3ncy** [comment]
@Pepepy 

cleo was recently bumped to version 2.0.0, maybe this is what is causing conflict?
Have you tried modifying the requirements.txt file to how it was previously?
It seems that cleo 2.0.0 needs a crashtest version below 0.5.0 and above 0.4.1, but clikit 0.6.2 needs crashtest version in between 0.4.0 and 0.3.0

<img width="630"  src="https://user-images.githubusercontent.com/104733166/205438073-d62ade4e-30a8-4ea9-81c9-824f936d8516.png">

**Comment by stevenbraham** [comment]
@Pepepy  @C3n7ral051nt4g3ncy if you checkout commit [`#4c61a42514e7adf1fe9120473934f4e6d79a8516`](https://github.com/WebBreacher/WhatsMyName/commit/4c61a42514e7adf1fe9120473934f4e6d79a8516) it works. This is the last normal commit before the bots updated the dependencies.

**Comment by WebBreacher** [comment]
Hi all. I've adjusted the cleo version to be 0.8.1 or greater. Please let me know if this helps.

**Comment by stevenbraham** [comment]
@WebBreacher I pulled the latest version and instead of errors with cleo I now get issues with `poetry` and `poetry-core`

```
ERROR: Cannot install poetry-core==1.1.0a7 and poetry==1.1.14 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested poetry-core==1.1.0a7
    poetry 1.1.14 depends on poetry-core<1.1.0 and >=1.0.7
```

I think the best you could do is look at the commit history of [requirements.txt](https://github.com/WebBreacher/WhatsMyName/blob/main/whatsmyname/requirements.txt) and undo all the changes made by the GitHub dependency bot (and disable it if possible)

**Comment by WebBreacher** [comment]
done.
