### ISSUE TITLE
OSINTelligence 

### ISSUE THREAD

**Issue by C3n7ral051nt4g3ncy** [WebBreacher/WhatsMyName#650]
It may be a good idea to take off https://osintelligence.discourse.group from the `wmn-data.json`.

https://webcache.googleusercontent.com/search?q=cache:mJxC91LiT5EJ:https://osintelligence.discourse.group

@WebBreacher : Let me know if I can submit a PR to take it off, it doesn't look like its going to be back up.

**Comment by WebBreacher** [comment]
Please do.

**Comment by C3n7ral051nt4g3ncy** [comment]
Issue closed after PR #651
