### ISSUE TITLE
Please add 3rd YouTube site

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#661]
The `youtube.com/@{account}` accesses different accounts than our existing detections.

**Comment by WebBreacher** [comment]
@C3n7ral051nt4g3ncy

**Comment by C3n7ral051nt4g3ncy** [comment]
Ok, I will add `youtube.com/@{account}`, this is the new username system they put in place a few months back

**Comment by WebBreacher** [comment]
Yes. I had thought back then that it was "covered" by our existing detections but I was wrong. Found one (I cannot give it since it is part of a case) that only shows with this URL

**Comment by WebBreacher** [comment]
hmm...I'm getting a fine response with a VPN and curl to `https://www.youtube.com/@cybersecuritymeg` with no redirect.

**Comment by C3n7ral051nt4g3ncy** [comment]
Ok, will try again,  tool must be faulty today.

**Comment by C3n7ral051nt4g3ncy** [comment]
Has been added --> PR #662

**Comment by WebBreacher** [comment]
Added with #662 - Thank you @C3n7ral051nt4g3ncy !
