### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by kenchas** [WebBreacher/WhatsMyName#664]
Installation fails on line 93 of requirements.txt:  twint @ file:///home/dcardin/Projects/twint

**Comment by WebBreacher** [comment]
Did you mean to post this in the twint GitHub repository instead of WhatsMyName? If not, then we are going to need many more details.

**Comment by kenchas** [comment]
Hi Micah,

It's the Whats My Name installation that fails.  I'm following the 
guidance in Michael Bazzell's OSINT Techniques 9th edition.  The 
installation is on a VirtualBox VM of Ubuntu 22.10 and the installation 
routine is:

cd ~/Downloads/Programs
git clone https://github.com/WebBreacher/WhatsMyName.git
cd WhatsMyName/whatsmyname
python3 -m venv WhatsMyNameEnvironment
source WhatsMyNameEnvironment/bin/activate
sudo pip install -r requirements.txt
deactivate

So a virtual environment.  It fails on sudo pip install -r 
requirements.txt with the following error message:

$ sudo pip install -r requirements.txt

Processing /home/dcardin/Projects/twint

ERROR: Could not install packages due to an OSError: [Errno 2] No such 
file or directory: '/home/dcardin/Projects/twint'

That's line 93 in the requirements.txt on the repository.

I'd noticed that the file was changed last week and wondered whether a 
mistake had been made.

Let me know if you need more information.

Best regards

Tony

**Comment by WebBreacher** [comment]
Ahhh. That helps! I've removed the twint reference. Please do a `git pull` or `git fetch` and try again.

**Comment by kenchas** [comment]
Hi Micah,

That's perfect!  Thanks for the speedy assistance.

Best Regards

Tony
