### ISSUE TITLE
Best way of dealing with outdated sites in the list

### ISSUE THREAD

**Issue by swedishmike** [WebBreacher/WhatsMyName#711]
I've finally found some mojo to try and sort my WMN_screenshooter app.

During that I have found that there's some sites in wmn-data.json that no longer seems to resolve/exist.

What is your preferred way for me to report/fix this @WebBreacher?

Do you want me to list them in an Issue for verification, submit PR's for each one or what's the best way for you?

I guess this could be since resources like https://whatsmyname.app/ doesn't really show any errors, whereas my cli based script does.

**Comment by WebBreacher** [comment]
Would love PRs with the sites fixed or removed (if they cannot be resolved). If you only have time to identify sites and not fix them, then make issues and I/the community will address them.

As always, really appreciate you looking at this.

**Comment by swedishmike** [comment]
Sure thing - I'll start identifying them and commit separate PRs.

Absolutely no worries at all - just glad to be able to help/give something back. Even if it's just a small bit.

**Comment by swedishmike** [comment]
What I've found so far have been submitted and accepted. Closing.
