### ISSUE TITLE
Data quality issues

### ISSUE THREAD

**Issue by swedishmike** [WebBreacher/WhatsMyName#717]
Since I've returned focus a bit onto my Osint interest and have sorted out my WMN_Screenshooter project to work with the new data format, finally, I've been running a number of checks.

It _looks_ like quite a lot of the 'known' usernames are no longer working, some 'strings' are potentially not correct any longer and so on.

So far I've just created a verification script that takes the known usernames and ships an error to screen if that doesn't work.

Before I go any further @WebBreacher, is anyone else doing the same work or should I just keep looking, verifying, trying to fix and submit PR's?

Don't want to waste mine or other people's time if it's not needed.

**Comment by swedishmike** [comment]
I've had a quick - and very random - look at some of the failures and it seems to be a mix of removed usernames, strings no longer existing and so on.

If it's ok with you I'll just go through them, test thoroughly if I find fixes and submit PR's.

**Comment by WebBreacher** [comment]
Please just continue to submit PRs for the fixes. Appreciate it. Smaller, more frequent PRs are helpful. Large ones with many sites changed takes longer to process

**Comment by swedishmike** [comment]
Cool - just held off further additions until you had ok'd the process etc. Will keep plugging away now.
