### ISSUE TITLE
counter.social - best approach?

### ISSUE THREAD

**Issue by swedishmike** [WebBreacher/WhatsMyName#720]
It seems that this site have added the option/necessity to enable your profile to be public.

What should the approach be here? Should we stick to the 'verify presence' ethos and trigger on that message[1]? That in itself should be verification that an account exists. If anyone knows of an existing account with an public profile I could see if there's anything that hits both public and private + e_code 200? 

Current setting:

       {
        "name" : "Mastodon-counter.social",
        "uri_check" : "https://counter.social/@{account}",
        "e_code" : 200,
        "e_string" : "@counter.social) - CounterSocial</title>",
        "m_string" : "The page you are looking for isn&#39;t here.",
        "m_code" : 404,
        "known" : ["ericconrad", "webbreacher"],
        "cat" : "social",
        "valid" : true
       },

[1]
<img width="666" alt="image" src="https://github.com/WebBreacher/WhatsMyName/assets/8100625/3e41b22b-b3cc-4f29-9cd0-ca71dfbf5b63">

**Comment by swedishmike** [comment]
Actually - looking at it deeper, it 302's from/via Cloudflare. 

I'm seeing that for a fair few others, that I've parked for now. Are Cloudflare fronted sites 'fixable' or should they just be dropped from the wmn-data.json? 

The only way I can see to deal with this would be to initially follow the redirect and then look for the next code/page so to speak?

If that's even doable in a sane way - would that necessitate anoother field in the json? Something like 

   {
    "name" : "Mastodon-counter.social",
    "uri_check" : "https://counter.social/@{account}",
    "e_code" : 200,
    "e_string" : "@counter.social) - CounterSocial</title>",
    "m_string" : "The page you are looking for isn&#39;t here.",
    "m_code" : 404,
    "known" : ["ericconrad", "webbreacher"],
    "cat" : "social",
    "follow_redirect" : true,
    "valid" : true
   },

**Comment by WebBreacher** [comment]
Once a site goes behind CF we stop accessing it. Just add it and the others you are removing to the https://github.com/WebBreacher/WhatsMyName/wiki/Problem-Removed-Sites wiki page and remove from the JSON please.

**Comment by swedishmike** [comment]
Will do - seems to be a fair few of them around.
