### ISSUE TITLE
Truth Social URLs are case sensitive

### ISSUE THREAD

**Issue by jocejocejoe** [WebBreacher/WhatsMyName#732]
I'm not sure if there's an easy way around this, but I'll point it out:

The Truth Social account lookup succeeds in a case-insensitive manner with the `uri_check`, for example this lower-case lookup succeeds:

[https://truthsocial.com/api/v1/accounts/lookup?acct=realdonaldtrump](https://truthsocial.com/api/v1/accounts/lookup?acct=realdonaldtrump)

and returns the following account URL in the json response, with different capitalization:

`"url":"https://truthsocial.com/@realDonaldTrump"`

However, case matters on the site; 

[https://truthsocial.com/@realDonaldTrump](https://truthsocial.com/@realDonaldTrump) works, but
[https://truthsocial.com/@realdonaldtrump](https://truthsocial.com/@realdonaldtrump) does not.

This means that the prety URI `"uri_pretty" : "https://www.truthsocial.com/@{account}",` which uses the original search account name with original capitalization, may not find the account.

I don't think there's currently any mechanism to incorporate the exact query results into the `uri_pretty`, but it seems like that's what it would take ro resolve this.

**Comment by WebBreacher** [comment]
Ooooo. Good catch and I see exactly what you are saying here. The WMN tool does not have a method of fixing this aside from removing the `uri_pretty` and just pointing to the API page. I think that'd be the best thing as it'll show the exact caps to use. 

What do you think about us removing the `uri_pretty` @jocejocejoe ?

**Comment by WebBreacher** [comment]
Implemented change.

**Comment by jocejocejoe** [comment]
Sorry for the slow response. Seems like a reasonable fix for now. Thanks!
