### ISSUE TITLE
AV starts blocking site

### ISSUE THREAD

**Issue by coderbm1** [WebBreacher/WhatsMyName#758]
"Type: Risk of data loss"
`https://late-tooth-b0bf.ocemail.workers.dev/?https://raw.githubusercontent.com/WebBreacher/WhatsMyName/main/wmn-data.json`

Kind regards

**Comment by coderbm1** [comment]
Please check results with virustotal

**Comment by coderbm1** [comment]
Hello @WebBreacher - web app
https://www.virustotal.com/gui/url/2491c2a974e11954fc47045902dbdd286986a702d4f4fabf2278c1862f0a1fbc
`5 security vendors flagged this URL as malicious` Results:
```Avira Phishing
CyRadar Malicious
Forcepoint ThreatSeeker Phishing
Kaspersky Phishing
Netcraft Malicious
alphaMountain.ai Suspicious```

(first post here - above)
It's about mentioned link. (from AV alert - result is blocked site there)

Interesting, because virustotal for 'https://whatsmyname.app/' looks fine: "No security vendors flagged this URL as malicious"

**Comment by coderbm1** [comment]
Sounds good, thanks a lot for quick action

**Comment by WebBreacher** [comment]
Follow up....we ended up changing the site to use a different worker and now the error should not show. Thank you for reporting this!
