### ISSUE TITLE
New site (showup.tv)

### ISSUE THREAD

**Issue by grabowskiadrian** [WebBreacher/WhatsMyName#764]
Hello, 

I'm trying to set up a request to showup.tv. This is a Polish NFSW sex cam site. This site has a process acceptance policy. Upon first request, the user must agree to the terms.

I found a solution to fix this case. It is necessary to set the **header to set the cookie**.

```
curl --location 'https://showup.tv/profile/Love_S' --header 'Cookie: accept_rules=true;'
```

Existing profiles: LunaVee, Jane_Frou, Love_S

If found: in html "<title>Profil"
HTTP: 200

If not found: in html "<title>Darmowe"
HTTP: 404

The question is: there is an option to add a header to set cookies? If so, I can implement this page.

**Comment by grabowskiadrian** [comment]
What script you use to check sites? 

On dev branch is old version i think.

**Comment by WebBreacher** [comment]
Yes. We removed the python checker from our repo earlier this year. We leave it to the developer/user to select the tool they use. Our README has a bunch you can choose from.

**Comment by grabowskiadrian** [comment]
I tried to use C3n7ral051nt4g3ncy/WhatsMyName-Python

but this tool not support headers.

I could make a fork (and add headers), but I want to be sure that the implementation will be the same as yours.

**Comment by WebBreacher** [comment]
The https://github.com/WebBreacher/WhatsMyName/issues/748 issue was recently closed. I'm not sure who has implemented headers in their checker.

**Comment by grabowskiadrian** [comment]
Ok, that's clear to me.

So the implementation logic is on the user/tool ​​side. The only important thing is to adapt to the schema (schema.json).

Thanks for the information. I will adapt one of the python tools to test sites

**Comment by WebBreacher** [comment]
Exactly. We moved from being an all-in-one JSON + python tool project to just focus on the JSON and deferring to the coders out there to make awesome checker tools. Makes our lives simpler to focus on detections.

**Comment by grabowskiadrian** [comment]
Pull request opened with new site. To test I used my new tool.

I made my own tool in which I implemented all the requirements from the wmn-data-schema.json file.

My tool also supports:
- post requests
- request headers

https://github.com/grabowskiadrian/WhatsMyName-Client

**Comment by WebBreacher** [comment]
Trying it out right now! Thanks for making this and sharing it. Would you want to add it to the README?

**Comment by grabowskiadrian** [comment]
If it's ok for you, I'll be happy to add it to the README

**Comment by WebBreacher** [comment]
Closing issue due to merge of #766
