### ISSUE TITLE
Bitbucket works again?

### ISSUE THREAD

**Issue by grabowskiadrian** [WebBreacher/WhatsMyName#765]
I tested bitbucket synchronization again. Right now this site is removed from wmn json file.

For curl request:
```
curl --location 'https://bitbucket.org/adriangrabowski4'
```

I received  **HTTP/2 200** 

Maybe it's time to add bitbucket again?

**Comment by grabowskiadrian** [comment]
Yup, site make redirect.

curl --location "https://bitbucket.org/adriangrabowski4"  -I | grep "HTTP"
HTTP/2 301 
HTTP/2 302 
HTTP/2 200

with /workspace/repositories/

curl --location "https://bitbucket.org/adriangrabowski4/workspace/repositories/"  -I | grep "HTTP"
HTTP/2 200 


So the correct URL for user is `https://bitbucket.org/{account}/workspace/repositories/`

**Comment by WebBreacher** [comment]
yes. that is correct. If you can visit the url directly and receive a correct response and no redirects to other pages (unless that is the "tell"), we would use the `https://bitbucket.org/{account}/workspace/repositories/` URL/URI
