### ISSUE TITLE
New Site: https://7nights.chatango.com/

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#771]
Examples:
https://7nights.chatango.com/
https://steakomura.chatango.com/
https://merbailey.chatango.com/
https://equicentric.chatango.com/

**Comment by grabowskiadrian** [comment]
`{
        "name" : "chatango.com",
        "uri_check" : "https://{account}.chatango.com",
        "e_code" : 200,
        "e_string" : "<title>Chatango!",
        "m_string" : "<title>Unknown User!",
        "m_code" : 200,
        "known" : ["7nights","merbailey", "steakomura", "equicentric"],
        "cat" : "social"
       }`
       
 My proposition. I will push it when my previous PRs are merged.

**Comment by WebBreacher** [comment]
Merged. Closing. Many thanks @grabowskiadrian
