### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by fres621** [WebBreacher/WhatsMyName#793]
Skype has an api that'd let you verify if an account exists by the username `https://avatar.skype.com/v1/avatars/USERNAME/public` (replace USERNAME with the desired username) however the only difference between a non existant account and an existant one is a response header "X-Avatar-Type: default" if the user requested doesn't exist, is this something WMN would be able to add or is a response content/status difference needed for WMN?

**Comment by WebBreacher** [comment]
Our detection strings are usually for the response data/content and not the headers. While we could add a detection for a header the absence of that header becomes even more challenging to check. Not in a programmatic way. Looking for the absence of something is not hard but, the tools that use the WMN JSON generally are looking for changes in the response body and not headers or the absence of headers. If we included this in WMN, none of the current downstream tools would check for it. They would have to be modified.
