### ISSUE TITLE
Page does not return any results / problem with fetch

### ISSUE THREAD

**Issue by Endtropy** [WebBreacher/WhatsMyName#794]
Hi, I tried to use a page yesterday but it stopped returning to me any results.  I took a look into the dev tool an it seems that the problem is in the fetching configuration json.  

The status for fetch: https://raw.githubusercontent.com/WebBreacher/WhatsMyName/main/wmn-data.json  
is  (failed)net::ERR_CERT_AUTHORITY_INVALID

It will be nice if the page will be back.  This page helps me a lot,

**Comment by WebBreacher** [comment]
Thanks for the submission. Can you tell us more about your setup?

1. What browser? Have you tried other ones?
2. What operating system?
3. Are you using a VPN? Have you tried without it?
4. Are you using certain security software on your computer that might block web browser activities? If so, which?
5. Does this happen on your mobile device too or just on your computer?

**Comment by Endtropy** [comment]
Hi, 
based on your questions i made few tests and found that the problem is no the side of my internet provider.
