### ISSUE TITLE
Add buymeacoffee.com

### ISSUE THREAD

**Issue by Doocter** [WebBreacher/WhatsMyName#799]
https://buymeacoffee.com/{username} (without @ in start)

Not found response status code: 404 Not Found
else Found

**Comment by WebBreacher** [comment]
Already included. 
![image](https://github.com/WebBreacher/WhatsMyName/assets/2359093/3422e81e-3842-4c0b-b070-095728a95f41)

Is it not finding the accounts you wanted?

**Comment by WebBreacher** [comment]
I checked the site and tweaked the missing and existing strings. Works for me. Unless you can provide more details about the profile you are searching and what app you are using (whatsmyname.app, a python checker, curl....), I cannot do anymore.
