### ISSUE TITLE
more sites

### ISSUE THREAD

**Issue by WebBreacher** [WebBreacher/WhatsMyName#8]
Look at knowem.com and namechk.com for more sites to enum

**Comment by aciwarrior** [comment]
Why vk.com is not on the list? 
Is there a problem in adding this one? Many hackers share the same twitter/vk handler - could be extremely useful in forensics.

**Comment by WebBreacher** [comment]
Great idea! I've done the first 150+ sites. I'm happy to accept additional submissions. Fork the project, add the content and do the pull request. Happy to add.

**Comment by WebBreacher** [comment]
@aciwarrior - took me a while but vk.com is on there now. Also vampirefreaks.com!
