### ISSUE TITLE
Consider Adding Hudson Rock Cybercrime Intelligence Free Integration

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [WebBreacher/WhatsMyName#806]
Consider adding Hudson Rock's complimentary data to receive additional intelligence about a username that was compromised in global Infostealer attacks.

Username sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-username?username=testadmin

Free API key and full documentation is available here: https://cavalier.hudsonrock.com/docs

Thank you.

**Comment by WebBreacher** [comment]
Done.
