### ISSUE TITLE
Add new metadata property to sites

### ISSUE THREAD

**Issue by p1ngul1n0** [WebBreacher/WhatsMyName#815]
Hi, first of all, congratulations on this project, it’s really helpful.

I have a suggestion to enhance the data enrichment during searches. In some cases, when a user is found, additional data such as Name, Location, Profile Picture, etc., can be extracted.

I propose adding a new property called "metadata". This property would enable any tool using the list to extract additional metadata. For JSON data, we could provide the JSON PATH to the desired data, and for HTML, we could use XPATH.

I understand that this might not work in all cases, such as with SPAs. However, I believe this enhancement would significantly improve the project's search capabilities.

Additionally, I recently updated my <a href="https://github.com/p1ngul1n0/blackbird">tool</a> to integrate with this project.

# Examples:

Acquiring Metadata in JSON:

```json
{
    "name": "Duolingo",
    "uri_check": "https://www.duolingo.com/2017-06-30/users?username={account}&_=1628308619574",
    "uri_pretty": "https://www.duolingo.com/profile/{account}",
    "e_code": 200,
    "e_string": "joinedClassroomIds",
    "m_string": "\"users\" : []",
    "m_code": 200,
    "known": [
        "sdfsdf",
        "duolingo"
    ],
    "cat": "hobby",
    "metadata": [
        {
            "schema": "JSON",
            "type": "String",
            "name": "Name",
            "path": [
                "users",
                0,
                "name"
            ]
        },
        {
            "schema": "JSON",
            "type": "String",
            "name": "Profile Picture",
            "path": [
                "users",
                0,
                "picture"
            ]
        }
    ]
},
```

Acquiring metadata in HTML:

```json
{
    "name": "Wireclub",
    "uri_check": "https://www.wireclub.com/users/{account}",
    "e_code": 200,
    "e_string": "Chat With",
    "m_string": "People - Wireclub",
    "m_code": 301,
    "known": [
        "deae",
        "cheerfulsarcasm",
        "braydenskiresort"
    ],
    "cat": "social",
    "metadata": [
        {
            "schema": "HTML",
            "type": "String",
            "name": "Name",
            "path": ["//*[@id=\"profile\"]/div[1]/h1"]
        },
        {
            "schema": "HTML",
            "type": "Image",
            "name": "Profile Picture",
            "path": ["//*[@id=\"profile\"]/div[1]/a/img"]
        }
    ]
},
```

**Comment by WebBreacher** [comment]
This is a great idea and way to implement it. Unfortunately, I and the many people that submit PRs have enough trouble trying to keep up with new sites to vet and fixing existing sites. I cannot imagine how much extra work this will be to map and maintain. Because if this, right now, I cannot see adding this metadata tag to the project at this time.

**Comment by p1ngul1n0** [comment]
Thank you for the feedback and I completely understand the additional workload this would create. I agree that maintaining the metadata would be challenging. However, I am excited about the possibility of integrating this feature in the future and will be eagerly waiting for when we can consider adding it to the project. Thank you for considering my suggestion, and I appreciate all the hard work you and the contributors put into maintaining this valuable resource.

**Comment by WebBreacher** [comment]
I appreciate you not only mentioning this feature request but coming up with the solution too! I wonder if you could create a side project with the metadata for each WMN entry since each `uri_check` is unique. Your project could, look at the `uri_check` and then look up a record/entity in your JSON for all the metadata associated with that `uri_check`, run the query and extract the results.

I know there are a bunch of paid tools that do this.

**Comment by p1ngul1n0** [comment]
Thank you for the suggestion! I think it's a great idea. I will implement this feature directly into my tool. Using `uri_check` to look up and extract associated metadata will significantly enhance its functionality. I'll start working on this integration and see how it can be effectively incorporated.

**Comment by p1ngul1n0** [comment]
Hi Micah,

Just to let you know, I've implemented metadata extraction in my tool. If you'd like to check it out, you can find it here. [https://github.com/p1ngul1n0/blackbird/blob/main/data/wmn-metadata.json](url)

**Comment by WebBreacher** [comment]
Thanks for the reference. I'll check it out!!
