### ISSUE TITLE
Site totally busted

### ISSUE THREAD

**Issue by parttimeamerican** [WebBreacher/WhatsMyName#818]
Tried 3 people
VPN's all over
none
nobody can get any results

likely need to rotate the API keys and IP etc

Can offer up use of my nord acc for 1 device maybe

**Comment by WebBreacher** [comment]
We are aware of the issues and working to fix them. See all our social media like https://x.com/whatsmynameproj/status/1792890883953525217 and https://www.linkedin.com/feed/update/urn:li:activity:7198656698092265473/.
