### ISSUE TITLE
Why did you pick the absolute worst captcha system?

### ISSUE THREAD

**Issue by ochompsky** [WebBreacher/WhatsMyName#829]
what system is this so i know to never use it myself?

**Comment by WebBreacher** [comment]
Hi. Sorry you are having challenges solving CAPTCHAs in the free whatsmyname.app. Please keep in mind that that client is just one of many that you can use and many of the others do not have a CAPTCHA. Check out the others here: https://github.com/WebBreacher/WhatsMyName?tab=readme-ov-file#toolsweb-sites-using-whatsmyname
