### ISSUE TITLE
It is possible to add these pages

### ISSUE THREAD

**Issue by danieldumma** [WebBreacher/WhatsMyName#832]
On June 18th, less than 1 month ago, Habbo Origins was released in English, Spanish, and Portuguese. Here it is for users to search

https://origins.habbo.com/api/public/users?name=username USA
https://origins.habbo.es/api/public/users?name=username Spain
https://origins.habbo.com.br/api/public/users?name=username Brazil

**Comment by WebBreacher** [comment]
Looking in our JSON file I see a bunch of Habbo sites. Can you look in https://github.com/WebBreacher/WhatsMyName/blob/main/wmn-data.json to see if the sites you want are in there?

If they are and are not working, that is a different issue. 

If they are not working, please write what client you use to check them (one of the python scripts, whatsmyname.app, etc.)

**Comment by WebBreacher** [comment]
I just ran the Whatsmyname-Python tool with the user name of "juan" and received these positive results for Habbo sites:
- Habbo.de:  https://www.habbo.de/api/public/users?name=juan
- Habbo.es:  https://www.habbo.es/api/public/users?name=juan
- Habbo.fr:  https://www.habbo.fr/api/public/users?name=juan
- Habbo.com.tr:  https://www.habbo.com.tr/api/public/users?name=juan
- Habbo.fi:  https://www.habbo.fi/api/public/users?name=juan
- Habbo.nl:  https://www.habbo.nl/api/public/users?name=juan

**Comment by danieldumma** [comment]
It's another Habbo, it's not the same Habbo. This is Habbo Origins, look at the API, the URL is different

**Comment by WebBreacher** [comment]
Thanks for the clarification. After checking the .es server you posted and the existing one in the project, I confirm the backend data sources contain different data. We can add the new URLs to the project.

**Comment by WebBreacher** [comment]
Done!
