### ISSUE TITLE
False Positives ru_123rf	& soloby	

### ISSUE THREAD

**Issue by horizonscanner** [WebBreacher/WhatsMyName#833]
Running usernames against whatsmyname will consistently bring up positive associations with ru_123rf	& soloby. 

See screenshots below with random username. 

<img width="744" alt="Screenshot 2024-07-12 at 10 38 27" src="https://github.com/user-attachments/assets/8888b27c-b25d-4dff-8d5c-63273547021f">

<img width="742" alt="Screenshot 2024-07-12 at 10 38 36" src="https://github.com/user-attachments/assets/ea7c3d20-cfb6-42f6-807f-927472fff947">

<img width="741" alt="Screenshot 2024-07-12 at 10 39 16" src="https://github.com/user-attachments/assets/744dc722-300e-4061-9ea7-2440fd48f075">

Forgot my password revealed that there is no account associated with the username given in Whatsmyname.

**Comment by WebBreacher** [comment]
Please recheck.
