### ISSUE TITLE
Questions about verification logic

### ISSUE THREAD

**Issue by Itsoon** [WebBreacher/WhatsMyName#841]
I have questions about certain cases and their meaning, which I haven't been able to figure out.
I describe them and hope that someone will be able to answer them.

If both `e_code` and `e_string` are valid, the account exists.
But if only one of them is valid, what does that mean?

If `e_string` and `m_string` are valid, it makes a false positive? If the answer is yes, can the false positive be resolved by revising the `e_string` and `m_string`?

If `m_code` is valid but `m_string` is invalid, it means what?

Thank you in advance for your reply

**Comment by WebBreacher** [comment]
1. e code and string match = positive hit
2. e code and e string only 1 match = error in our detections (need to change our detection strings and codes...make issue or PR)
3. e string and m string both valid = error in our detections (need to change our detection strings and codes...make issue or PR)
4. m code and m string only 1 match = error in our detections (need to change our detection strings and codes...make issue or PR)

**Comment by Itsoon** [comment]
Okay, that's much clearer. The last black spot, in which case is the result a false positive?

**Comment by Itsoon** [comment]
re: False positive would be where the e code and string are positive but there is no account there when you verify.

verification with what? Isn't WMN already used to check whether the account exists? What I'm trying to understand is how you get false positives on https://whatsmyname.app/.

**Comment by Itsoon** [comment]
Is there any particular reason why the "unknown username" field doesn't exist? This field, unlike the known field, would allow us to check whether the site is still returning positive results.

**Comment by WebBreacher** [comment]
Sorry for the delay here. In general, the reason is that it should be fairly simple to come up with a valid but unknown username for downstream scripts using a random number of certain characters.
