### ISSUE TITLE
CloudFlare

### ISSUE THREAD

**Issue by 3xp0rt** [WebBreacher/WhatsMyName#855]
I just discovered that you delete sites because of CloudFlare. However, CloudFlare can be easily bypassed using curl_cffi with a single line of Python code. I suggest tagging websites that use CloudFlare instead of deleting them. This avoids limiting functionality for tools capable of bypassing CloudFlare, etc.

**Comment by WebBreacher** [comment]
This is a good point we will consider. Thank you.

**Comment by WebBreacher** [comment]
Reopening this issue so that I can work on adding the new element to the schema.

**Comment by WebBreacher** [comment]
#879 Adds the `protection` schema element to address this.
