### ISSUE TITLE
False positive for yazawaj

### ISSUE THREAD

**Issue by arin17bishwa** [WebBreacher/WhatsMyName#862]
The username `teddyG` seems is not present on the platform, but it still showing false positive for https://www.yazawaj.com/
![image](https://github.com/user-attachments/assets/da3b7646-9a9c-4cde-9686-9c1976ac573f)

![image](https://github.com/user-attachments/assets/796618c7-0acd-41e2-9da9-67a8bbd7b450)

**Comment by WebBreacher** [comment]
The `e_string` was not correct. Fixing.

**Comment by WebBreacher** [comment]
#868 fixed
