### ISSUE TITLE
False positive for girlfriendsmeet

### ISSUE THREAD

**Issue by arin17bishwa** [WebBreacher/WhatsMyName#863]
Found false positive results for Girlfriendsmeet with username `teddyG`

![image](https://github.com/user-attachments/assets/0ba6df6b-058e-4c50-a77b-fb3d72a27427)

![image](https://github.com/user-attachments/assets/95d50f4e-b426-4a1b-99e7-7a3af2ece0cd)

**Comment by WebBreacher** [comment]
Yes. That site no longer exists. Removing it.

**Comment by WebBreacher** [comment]
#868 fixed
