### ISSUE TITLE
Support for GraphQL based search

### ISSUE THREAD

**Issue by arin17bishwa** [WebBreacher/WhatsMyName#865]
GraphQL-based searches are just POST calls, but the major difference is that the response has to be parsed and checked as JSON, not HTML. Also, it is almost always a 200 response code.
Is support for such lookups within this project's purview?

**Comment by WebBreacher** [comment]
I think it would be as we accept POST entries and there would be strings coming back.

**Comment by WebBreacher** [comment]
I'm going to say "yes" and downstream tools can figure out how to parse it. Sites like anobii and caringbridge have moved to graphql so this is good timing.
