### ISSUE TITLE
MANYVIDS False Positive

### ISSUE THREAD

**Issue by FlexilisPullum** [WebBreacher/WhatsMyName#892]
**Version:** whatsmyname.app
**Issue:** False positive results for MANYVIDS accounts
**Steps to recreate:** Run a "All" or "NSFW" search on any random string
![Screenshot 2024-10-16 165541](https://github.com/user-attachments/assets/41b40cc3-5f59-402c-8da5-e1d76746735e)

**Comment by WebBreacher** [comment]
Yes. This is a tough one. To check MANYVIDS we have to use their search (`https://www.manyvids.com/bff/search/results?keywords={account}`) and it sometimes returns content that are false positives. I thought of removing it but, when you DO get a good username hit, it is good. So, for now, until we create a better detection, we need to leave this.

**Comment by 3xp0rt** [comment]
There is a `slug` key, which can be used something like `"e_string" : "\"slug\":\"{account}\""`. However, this would require updating the tools that rely on this dataset and schema. But from a future perspective, this is good because it expands the functionality.

**Comment by FlexilisPullum** [comment]
Interesting. whatsmyname.app has a false positive section, but I assume that it's a part of that ui and not the program itself then?

**Comment by WebBreacher** [comment]
That's a part of the app and how they use the e and m codes and strings. 

But this repo is not for that app which is coded privately and privately hosted.

**Comment by FlexilisPullum** [comment]
That's fair, sorry for the confusion.

**Comment by 3xp0rt** [comment]
> Yes. This is a tough one. To check MANYVIDS we have to use their search (`https://www.manyvids.com/bff/search/results?keywords={account}`) and it sometimes returns content that are false positives. I thought of removing it but, when you DO get a good username hit, it is good. So, for now, until we create a better detection, we need to leave this.

It doesn't just sometimes return false positives; it always does. For instance, even a query like https://www.manyvids.com/bff/search/results?keywords=4393943434312332432543 will generate results. Keeping this site on the list is completely unjustifiable. To verify whether it's a legitimate positive, you have to visit the site and manually check. This can be done without the help of WhatsMyName—just manually.

**Comment by WebBreacher** [comment]
Hmmm...interesting thoughts. Let me think on this.
