### ISSUE TITLE
Manyvids False Positives

### ISSUE THREAD

**Issue by MillerMedia** [WebBreacher/WhatsMyName#914]
I was using the site at whatsmyname.app and noticed that I am getting false positives on the Manyvids search. It resolves to an address like https://www.manyvids.com/results.php?keywords={USERNAME} which always returns search results. It does not seem to confirm though whether, within that search, there is an account with that username.

**Comment by WebBreacher** [comment]
Thanks for the issue. And yes, this gives false positives. Please refer to my response in issue #892 

"Yes. This is a tough one. To check MANYVIDS we have to use their search (https://www.manyvids.com/bff/search/results?keywords={account}) and it sometimes returns content that are false positives. I thought of removing it but, when you DO get a good username hit, it is good. So, for now, until we create a better detection, we need to leave this."
